/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import static java.lang.System.exit;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Hebron Hossain Hamim
 */
public class BalanceCheck extends javax.swing.JFrame {

    /**
     * Creates new form BalanceCheck
     */
    
    LogIn lcw = new LogIn();
    Method mcw = new Method();
    Home h = new Home();
    
    private String userName;
    private String pass;
    String number, cb;
    String arr1[] = new String[40];
    double df, du, mr;

    public BalanceCheck(String userName, String pass) {
        this.userName = userName;
        this.pass = pass;
        initComponents();
        
        jKeyBoardLabelBC.setVisible(false);
        jButton1BC.setVisible(false);
        jButton2BC.setVisible(false);
        jButton3BC.setVisible(false);
        jButton4BC.setVisible(false);
        jButton5BC.setVisible(false);
        jButton6BC.setVisible(false);
        jButton7BC.setVisible(false);
        jButton8BC.setVisible(false);
        jButton9BC.setVisible(false);
        jButton0BC.setVisible(false);

        try {
            FileReader fr = new FileReader("login.txt");
            BufferedReader br = new BufferedReader(fr);
            String line;
            while ((line = br.readLine()) != null) {
                arr1 = line.split("#");
                if (arr1[0].equals(userName) && arr1[1].equals(pass)) {
                    cb = arr1[3];
                    System.out.println(cb);
                }
            }
            br.close();
        } catch (IOException ex) {
            Logger.getLogger(CashWithdraw.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public BalanceCheck() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBalanceCheckLabelBC = new javax.swing.JLabel();
        jBalanceLabelBC = new javax.swing.JLabel();
        jTextFieldBC = new javax.swing.JTextField();
        jShowBalButtonBC = new javax.swing.JButton();
        jBackButtonBC = new javax.swing.JButton();
        jLogOutButtonBC = new javax.swing.JButton();
        jButton1BC = new javax.swing.JButton();
        jButton2BC = new javax.swing.JButton();
        jButton3BC = new javax.swing.JButton();
        jButton4BC = new javax.swing.JButton();
        jButton5BC = new javax.swing.JButton();
        jButton6BC = new javax.swing.JButton();
        jButton7BC = new javax.swing.JButton();
        jButton8BC = new javax.swing.JButton();
        jButton9BC = new javax.swing.JButton();
        jButton0BC = new javax.swing.JButton();
        jKeyBoardLabelBC = new javax.swing.JLabel();
        jBackgroundLabelBC = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBalanceCheckLabelBC.setBackground(new java.awt.Color(255, 255, 255));
        jBalanceCheckLabelBC.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jBalanceCheckLabelBC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jBalanceCheckLabelBC.setText("Balance Check");
        jBalanceCheckLabelBC.setOpaque(true);
        jPanel1.add(jBalanceCheckLabelBC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 650, 50));

        jBalanceLabelBC.setBackground(new java.awt.Color(255, 255, 255));
        jBalanceLabelBC.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jBalanceLabelBC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jBalanceLabelBC.setText("Current Balance");
        jBalanceLabelBC.setOpaque(true);
        jPanel1.add(jBalanceLabelBC, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 250, 40));

        jTextFieldBC.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jTextFieldBC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldBC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBCActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldBC, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 200, 40));

        jShowBalButtonBC.setBackground(new java.awt.Color(0, 0, 0));
        jShowBalButtonBC.setFont(new java.awt.Font("Agency FB", 1, 30)); // NOI18N
        jShowBalButtonBC.setForeground(new java.awt.Color(255, 255, 255));
        jShowBalButtonBC.setText("Show Balance");
        jShowBalButtonBC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jShowBalButtonBCActionPerformed(evt);
            }
        });
        jPanel1.add(jShowBalButtonBC, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 190, 50));

        jBackButtonBC.setBackground(new java.awt.Color(0, 0, 0));
        jBackButtonBC.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jBackButtonBC.setForeground(new java.awt.Color(255, 255, 255));
        jBackButtonBC.setText("Back");
        jBackButtonBC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBackButtonBCActionPerformed(evt);
            }
        });
        jPanel1.add(jBackButtonBC, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, 190, 50));

        jLogOutButtonBC.setBackground(new java.awt.Color(255, 0, 0));
        jLogOutButtonBC.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLogOutButtonBC.setText("Log Out");
        jLogOutButtonBC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogOutButtonBCActionPerformed(evt);
            }
        });
        jPanel1.add(jLogOutButtonBC, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 490, 190, 50));

        jButton1BC.setBackground(new java.awt.Color(0, 0, 0));
        jButton1BC.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jButton1BC.setForeground(new java.awt.Color(255, 255, 255));
        jButton1BC.setText("1");
        jPanel1.add(jButton1BC, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 60, 40));

        jButton2BC.setBackground(new java.awt.Color(0, 0, 0));
        jButton2BC.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jButton2BC.setForeground(new java.awt.Color(255, 255, 255));
        jButton2BC.setText("2");
        jPanel1.add(jButton2BC, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 60, 40));

        jButton3BC.setBackground(new java.awt.Color(0, 0, 0));
        jButton3BC.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jButton3BC.setForeground(new java.awt.Color(255, 255, 255));
        jButton3BC.setText("3");
        jPanel1.add(jButton3BC, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 60, 40));

        jButton4BC.setBackground(new java.awt.Color(0, 0, 0));
        jButton4BC.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jButton4BC.setForeground(new java.awt.Color(255, 255, 255));
        jButton4BC.setText("4");
        jPanel1.add(jButton4BC, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 60, 40));

        jButton5BC.setBackground(new java.awt.Color(0, 0, 0));
        jButton5BC.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jButton5BC.setForeground(new java.awt.Color(255, 255, 255));
        jButton5BC.setText("5");
        jPanel1.add(jButton5BC, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 60, 40));

        jButton6BC.setBackground(new java.awt.Color(0, 0, 0));
        jButton6BC.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jButton6BC.setForeground(new java.awt.Color(255, 255, 255));
        jButton6BC.setText("6");
        jPanel1.add(jButton6BC, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 60, 40));

        jButton7BC.setBackground(new java.awt.Color(0, 0, 0));
        jButton7BC.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jButton7BC.setForeground(new java.awt.Color(255, 255, 255));
        jButton7BC.setText("7");
        jPanel1.add(jButton7BC, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 60, 40));

        jButton8BC.setBackground(new java.awt.Color(0, 0, 0));
        jButton8BC.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jButton8BC.setForeground(new java.awt.Color(255, 255, 255));
        jButton8BC.setText("8");
        jPanel1.add(jButton8BC, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, 60, 40));

        jButton9BC.setBackground(new java.awt.Color(0, 0, 0));
        jButton9BC.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jButton9BC.setForeground(new java.awt.Color(255, 255, 255));
        jButton9BC.setText("9");
        jPanel1.add(jButton9BC, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, 60, 40));

        jButton0BC.setBackground(new java.awt.Color(0, 0, 0));
        jButton0BC.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jButton0BC.setForeground(new java.awt.Color(255, 255, 255));
        jButton0BC.setText("0");
        jPanel1.add(jButton0BC, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 490, 60, 40));

        jKeyBoardLabelBC.setBackground(new java.awt.Color(255, 255, 255));
        jKeyBoardLabelBC.setOpaque(true);
        jPanel1.add(jKeyBoardLabelBC, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 340, 180));

        jBackgroundLabelBC.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hebron Hossain Hamim\\Desktop\\ATM Project\\Images\\bnwb.jpg")); // NOI18N
        jBackgroundLabelBC.setText("jLabel1");
        jPanel1.add(jBackgroundLabelBC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBackButtonBCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBackButtonBCActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jBackButtonBCActionPerformed

    private void jTextFieldBCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBCActionPerformed

    private void jLogOutButtonBCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLogOutButtonBCActionPerformed
        // TODO add your handling code here:
        lcw.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLogOutButtonBCActionPerformed

    private void jShowBalButtonBCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jShowBalButtonBCActionPerformed
        // TODO add your handling code here:
        jTextFieldBC.setText(cb + " " + "BDT");
    }//GEN-LAST:event_jShowBalButtonBCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BalanceCheck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BalanceCheck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BalanceCheck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BalanceCheck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BalanceCheck().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBackButtonBC;
    private javax.swing.JLabel jBackgroundLabelBC;
    private javax.swing.JLabel jBalanceCheckLabelBC;
    private javax.swing.JLabel jBalanceLabelBC;
    private javax.swing.JButton jButton0BC;
    private javax.swing.JButton jButton1BC;
    private javax.swing.JButton jButton2BC;
    private javax.swing.JButton jButton3BC;
    private javax.swing.JButton jButton4BC;
    private javax.swing.JButton jButton5BC;
    private javax.swing.JButton jButton6BC;
    private javax.swing.JButton jButton7BC;
    private javax.swing.JButton jButton8BC;
    private javax.swing.JButton jButton9BC;
    private javax.swing.JLabel jKeyBoardLabelBC;
    private javax.swing.JButton jLogOutButtonBC;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jShowBalButtonBC;
    private javax.swing.JTextField jTextFieldBC;
    // End of variables declaration//GEN-END:variables
}
