/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Hebron Hossain Hamim
 */
public class BillPay extends javax.swing.JFrame {

    /**
     * Creates new form BillPay
     */
    private String userName;
    private String pass;
    String number1, number2, number3, cv;
    LogIn lcw = new LogIn();
    Method mcw = new Method();
    String arr1[] = new String[40];
    double df, du, mr;
    int mouse1, mouse2, mouse3;

    public BillPay(String userName, String pass) {
        this.userName = userName;
        this.pass = pass;
        initComponents();

        String sourceFileName = "login.txt";
        String destinationFileName = "temp.txt";

        try {
            BufferedReader br = new BufferedReader(new FileReader(sourceFileName));
            PrintWriter pw = new PrintWriter(new FileWriter(destinationFileName));

            String line;
            while ((line = br.readLine()) != null) {
                pw.write(line);
                pw.println();
            }

            br.close();
            pw.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public BillPay() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBillPayLabelBP = new javax.swing.JLabel();
        jBillerIdLabelBP = new javax.swing.JLabel();
        jRefNoLabelBP = new javax.swing.JLabel();
        jAmountLabelBp = new javax.swing.JLabel();
        jBIDTextFieldBP = new javax.swing.JTextField();
        jRNoTextFieldBP = new javax.swing.JTextField();
        jAmountTextFieldBP = new javax.swing.JTextField();
        jClearBIDButtonBP = new javax.swing.JButton();
        jClearRNButtonBP = new javax.swing.JButton();
        jClearMAButtonBP = new javax.swing.JButton();
        jSubmitButtonBP = new javax.swing.JButton();
        jBackButtonBp = new javax.swing.JButton();
        jLogOutButtonBP = new javax.swing.JButton();
        jButton1BP = new javax.swing.JButton();
        jButton2BP = new javax.swing.JButton();
        jButton3BP = new javax.swing.JButton();
        jButton4BP = new javax.swing.JButton();
        jButton5BP = new javax.swing.JButton();
        jButton6BP = new javax.swing.JButton();
        jButton7BP = new javax.swing.JButton();
        jButton8BP = new javax.swing.JButton();
        jButton9BP = new javax.swing.JButton();
        jButton0BP = new javax.swing.JButton();
        jKeyBoardLabelBP = new javax.swing.JLabel();
        jBackgroundLabelBP = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBillPayLabelBP.setBackground(new java.awt.Color(255, 255, 255));
        jBillPayLabelBP.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jBillPayLabelBP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jBillPayLabelBP.setText("Bill Pay");
        jBillPayLabelBP.setOpaque(true);
        jPanel1.add(jBillPayLabelBP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 650, 50));

        jBillerIdLabelBP.setBackground(new java.awt.Color(255, 255, 255));
        jBillerIdLabelBP.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jBillerIdLabelBP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jBillerIdLabelBP.setText("Biller ID");
        jBillerIdLabelBP.setOpaque(true);
        jPanel1.add(jBillerIdLabelBP, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 250, 40));

        jRefNoLabelBP.setBackground(new java.awt.Color(255, 255, 255));
        jRefNoLabelBP.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jRefNoLabelBP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRefNoLabelBP.setText("Reference No.");
        jRefNoLabelBP.setOpaque(true);
        jPanel1.add(jRefNoLabelBP, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 250, 40));

        jAmountLabelBp.setBackground(new java.awt.Color(255, 255, 255));
        jAmountLabelBp.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jAmountLabelBp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jAmountLabelBp.setText("Input Amount Of Money");
        jAmountLabelBp.setOpaque(true);
        jPanel1.add(jAmountLabelBp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 250, 40));

        jBIDTextFieldBP.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jBIDTextFieldBP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jBIDTextFieldBP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBIDTextFieldBPMouseClicked(evt);
            }
        });
        jBIDTextFieldBP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBIDTextFieldBPActionPerformed(evt);
            }
        });
        jPanel1.add(jBIDTextFieldBP, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 200, 40));

        jRNoTextFieldBP.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jRNoTextFieldBP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jRNoTextFieldBP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRNoTextFieldBPMouseClicked(evt);
            }
        });
        jRNoTextFieldBP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRNoTextFieldBPActionPerformed(evt);
            }
        });
        jPanel1.add(jRNoTextFieldBP, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 200, 40));

        jAmountTextFieldBP.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jAmountTextFieldBP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jAmountTextFieldBP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jAmountTextFieldBPMouseClicked(evt);
            }
        });
        jAmountTextFieldBP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAmountTextFieldBPActionPerformed(evt);
            }
        });
        jPanel1.add(jAmountTextFieldBP, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 200, 40));

        jClearBIDButtonBP.setBackground(new java.awt.Color(0, 0, 0));
        jClearBIDButtonBP.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jClearBIDButtonBP.setForeground(new java.awt.Color(255, 255, 255));
        jClearBIDButtonBP.setText("Clear");
        jClearBIDButtonBP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClearBIDButtonBPActionPerformed(evt);
            }
        });
        jPanel1.add(jClearBIDButtonBP, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, 70, 40));

        jClearRNButtonBP.setBackground(new java.awt.Color(0, 0, 0));
        jClearRNButtonBP.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jClearRNButtonBP.setForeground(new java.awt.Color(255, 255, 255));
        jClearRNButtonBP.setText("Clear");
        jClearRNButtonBP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClearRNButtonBPActionPerformed(evt);
            }
        });
        jPanel1.add(jClearRNButtonBP, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, 70, 40));

        jClearMAButtonBP.setBackground(new java.awt.Color(0, 0, 0));
        jClearMAButtonBP.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jClearMAButtonBP.setForeground(new java.awt.Color(255, 255, 255));
        jClearMAButtonBP.setText("Clear");
        jClearMAButtonBP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClearMAButtonBPActionPerformed(evt);
            }
        });
        jPanel1.add(jClearMAButtonBP, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, 70, 40));

        jSubmitButtonBP.setBackground(new java.awt.Color(0, 153, 0));
        jSubmitButtonBP.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jSubmitButtonBP.setForeground(new java.awt.Color(255, 255, 255));
        jSubmitButtonBP.setText("Submit");
        jSubmitButtonBP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubmitButtonBPActionPerformed(evt);
            }
        });
        jPanel1.add(jSubmitButtonBP, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 190, 50));

        jBackButtonBp.setBackground(new java.awt.Color(0, 0, 0));
        jBackButtonBp.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jBackButtonBp.setForeground(new java.awt.Color(255, 255, 255));
        jBackButtonBp.setText("Back");
        jBackButtonBp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBackButtonBpActionPerformed(evt);
            }
        });
        jPanel1.add(jBackButtonBp, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, 190, 50));

        jLogOutButtonBP.setBackground(new java.awt.Color(255, 0, 0));
        jLogOutButtonBP.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLogOutButtonBP.setForeground(new java.awt.Color(255, 255, 255));
        jLogOutButtonBP.setText("Log Out");
        jLogOutButtonBP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogOutButtonBPActionPerformed(evt);
            }
        });
        jPanel1.add(jLogOutButtonBP, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 490, 190, 50));

        jButton1BP.setBackground(new java.awt.Color(0, 0, 0));
        jButton1BP.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jButton1BP.setForeground(new java.awt.Color(255, 255, 255));
        jButton1BP.setText("1");
        jButton1BP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1BPActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1BP, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 60, 40));

        jButton2BP.setBackground(new java.awt.Color(0, 0, 0));
        jButton2BP.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jButton2BP.setForeground(new java.awt.Color(255, 255, 255));
        jButton2BP.setText("2");
        jButton2BP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2BPActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2BP, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 60, 40));

        jButton3BP.setBackground(new java.awt.Color(0, 0, 0));
        jButton3BP.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jButton3BP.setForeground(new java.awt.Color(255, 255, 255));
        jButton3BP.setText("3");
        jButton3BP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3BPActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3BP, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 60, 40));

        jButton4BP.setBackground(new java.awt.Color(0, 0, 0));
        jButton4BP.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jButton4BP.setForeground(new java.awt.Color(255, 255, 255));
        jButton4BP.setText("4");
        jButton4BP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4BPActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4BP, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 60, 40));

        jButton5BP.setBackground(new java.awt.Color(0, 0, 0));
        jButton5BP.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jButton5BP.setForeground(new java.awt.Color(255, 255, 255));
        jButton5BP.setText("5");
        jButton5BP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5BPActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5BP, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 60, 40));

        jButton6BP.setBackground(new java.awt.Color(0, 0, 0));
        jButton6BP.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jButton6BP.setForeground(new java.awt.Color(255, 255, 255));
        jButton6BP.setText("6");
        jButton6BP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6BPActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6BP, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 60, 40));

        jButton7BP.setBackground(new java.awt.Color(0, 0, 0));
        jButton7BP.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jButton7BP.setForeground(new java.awt.Color(255, 255, 255));
        jButton7BP.setText("7");
        jButton7BP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7BPActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7BP, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 60, 40));

        jButton8BP.setBackground(new java.awt.Color(0, 0, 0));
        jButton8BP.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jButton8BP.setForeground(new java.awt.Color(255, 255, 255));
        jButton8BP.setText("8");
        jButton8BP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8BPActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8BP, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, 60, 40));

        jButton9BP.setBackground(new java.awt.Color(0, 0, 0));
        jButton9BP.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jButton9BP.setForeground(new java.awt.Color(255, 255, 255));
        jButton9BP.setText("9");
        jButton9BP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9BPActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9BP, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, 60, 40));

        jButton0BP.setBackground(new java.awt.Color(0, 0, 0));
        jButton0BP.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jButton0BP.setForeground(new java.awt.Color(255, 255, 255));
        jButton0BP.setText("0");
        jButton0BP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton0BPActionPerformed(evt);
            }
        });
        jPanel1.add(jButton0BP, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 490, 60, 40));

        jKeyBoardLabelBP.setBackground(new java.awt.Color(255, 255, 255));
        jKeyBoardLabelBP.setOpaque(true);
        jPanel1.add(jKeyBoardLabelBP, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 340, 180));

        jBackgroundLabelBP.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hebron Hossain Hamim\\Desktop\\ATM Project\\Images\\bnwb.jpg")); // NOI18N
        jPanel1.add(jBackgroundLabelBP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1BPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1BPActionPerformed
        // TODO add your handling code here:
        if (mouse1 >= 1) {
            number1 = jBIDTextFieldBP.getText() + "1";
            jBIDTextFieldBP.setText(number1);
        } else if (mouse2 >= 1) {
            number2 = jRNoTextFieldBP.getText() + "1";
            jRNoTextFieldBP.setText(number2);
        } else if (mouse3 >= 1) {
            number3 = jAmountTextFieldBP.getText() + "1";
            jAmountTextFieldBP.setText(number3);
        }
    }//GEN-LAST:event_jButton1BPActionPerformed

    private void jButton2BPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2BPActionPerformed
        // TODO add your handling code here:
        if (mouse1 >= 1) {
            number1 = jBIDTextFieldBP.getText() + "2";
            jBIDTextFieldBP.setText(number1);
        } else if (mouse2 >= 1) {
            number2 = jRNoTextFieldBP.getText() + "2";
            jRNoTextFieldBP.setText(number2);
        } else if (mouse3 >= 1) {
            number3 = jAmountTextFieldBP.getText() + "2";
            jAmountTextFieldBP.setText(number3);
        }
    }//GEN-LAST:event_jButton2BPActionPerformed

    private void jButton3BPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3BPActionPerformed
        // TODO add your handling code here:
        if (mouse1 >= 1) {
            number1 = jBIDTextFieldBP.getText() + "3";
            jBIDTextFieldBP.setText(number1);
        } else if (mouse2 >= 1) {
            number2 = jRNoTextFieldBP.getText() + "3";
            jRNoTextFieldBP.setText(number2);
        } else if (mouse3 >= 1) {
            number3 = jAmountTextFieldBP.getText() + "3";
            jAmountTextFieldBP.setText(number3);
        }
    }//GEN-LAST:event_jButton3BPActionPerformed

    private void jButton4BPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4BPActionPerformed
        // TODO add your handling code here:
        if (mouse1 >= 1) {
            number1 = jBIDTextFieldBP.getText() + "4";
            jBIDTextFieldBP.setText(number1);
        } else if (mouse2 >= 1) {
            number2 = jRNoTextFieldBP.getText() + "4";
            jRNoTextFieldBP.setText(number2);
        } else if (mouse3 >= 1) {
            number3 = jAmountTextFieldBP.getText() + "4";
            jAmountTextFieldBP.setText(number3);
        }
    }//GEN-LAST:event_jButton4BPActionPerformed

    private void jButton5BPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5BPActionPerformed
        // TODO add your handling code here:
        if (mouse1 >= 1) {
            number1 = jBIDTextFieldBP.getText() + "5";
            jBIDTextFieldBP.setText(number1);
        } else if (mouse2 >= 1) {
            number2 = jRNoTextFieldBP.getText() + "5";
            jRNoTextFieldBP.setText(number2);
        } else if (mouse3 >= 1) {
            number3 = jAmountTextFieldBP.getText() + "5";
            jAmountTextFieldBP.setText(number3);
        }
    }//GEN-LAST:event_jButton5BPActionPerformed

    private void jButton6BPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6BPActionPerformed
        // TODO add your handling code here:
        if (mouse1 >= 1) {
            number1 = jBIDTextFieldBP.getText() + "6";
            jBIDTextFieldBP.setText(number1);
        } else if (mouse2 >= 1) {
            number2 = jRNoTextFieldBP.getText() + "6";
            jRNoTextFieldBP.setText(number2);
        } else if (mouse3 >= 1) {
            number3 = jAmountTextFieldBP.getText() + "6";
            jAmountTextFieldBP.setText(number3);
        }
    }//GEN-LAST:event_jButton6BPActionPerformed

    private void jButton7BPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7BPActionPerformed
        // TODO add your handling code here:
        if (mouse1 == 1) {
            number1 = jBIDTextFieldBP.getText() + "7";
            jBIDTextFieldBP.setText(number1);
        } else if (mouse2 == 1) {
            number2 = jRNoTextFieldBP.getText() + "7";
            jRNoTextFieldBP.setText(number2);
        } else if (mouse3 == 1) {
            number3 = jAmountTextFieldBP.getText() + "7";
            jAmountTextFieldBP.setText(number3);
        }
    }//GEN-LAST:event_jButton7BPActionPerformed

    private void jButton8BPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8BPActionPerformed
        // TODO add your handling code here:
        if (mouse1 >= 1) {
            number1 = jBIDTextFieldBP.getText() + "8";
            jBIDTextFieldBP.setText(number1);
        } else if (mouse2 >= 1) {
            number2 = jRNoTextFieldBP.getText() + "8";
            jRNoTextFieldBP.setText(number2);
        } else if (mouse3 >= 1) {
            number3 = jAmountTextFieldBP.getText() + "8";
            jAmountTextFieldBP.setText(number3);
        }
    }//GEN-LAST:event_jButton8BPActionPerformed

    private void jButton9BPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9BPActionPerformed
        // TODO add your handling code here:
        if (mouse1 >= 1) {
            number1 = jBIDTextFieldBP.getText() + "9";
            jBIDTextFieldBP.setText(number1);
        } else if (mouse2 >= 1) {
            number2 = jRNoTextFieldBP.getText() + "9";
            jRNoTextFieldBP.setText(number2);
        } else if (mouse3 >= 1) {
            number3 = jAmountTextFieldBP.getText() + "9";
            jAmountTextFieldBP.setText(number3);
        }
    }//GEN-LAST:event_jButton9BPActionPerformed

    private void jButton0BPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton0BPActionPerformed
        // TODO add your handling code here:
        if (mouse1 >= 1) {
            number1 = jBIDTextFieldBP.getText() + "0";
            jBIDTextFieldBP.setText(number1);
        } else if (mouse2 >= 1) {
            number2 = jRNoTextFieldBP.getText() + "0";
            jRNoTextFieldBP.setText(number2);
        } else if (mouse3 >= 1) {
            number3 = jAmountTextFieldBP.getText() + "0";
            jAmountTextFieldBP.setText(number3);
        }
    }//GEN-LAST:event_jButton0BPActionPerformed

    private void jBIDTextFieldBPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBIDTextFieldBPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBIDTextFieldBPActionPerformed

    private void jRNoTextFieldBPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRNoTextFieldBPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRNoTextFieldBPActionPerformed

    private void jAmountTextFieldBPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAmountTextFieldBPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAmountTextFieldBPActionPerformed

    private void jClearBIDButtonBPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClearBIDButtonBPActionPerformed
        // TODO add your handling code here:
        jBIDTextFieldBP.setText("");
        number1 = "";
    }//GEN-LAST:event_jClearBIDButtonBPActionPerformed

    private void jClearRNButtonBPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClearRNButtonBPActionPerformed
        // TODO add your handling code here:
        jRNoTextFieldBP.setText("");
        number2 = "";
    }//GEN-LAST:event_jClearRNButtonBPActionPerformed

    private void jClearMAButtonBPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClearMAButtonBPActionPerformed
        // TODO add your handling code here:
        jAmountTextFieldBP.setText("");
        number3 = "";
    }//GEN-LAST:event_jClearMAButtonBPActionPerformed

    private void jBIDTextFieldBPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBIDTextFieldBPMouseClicked
        // TODO add your handling code here:
        mouse1 = 1;
        mouse2 = 0;
        mouse3 = 0;
    }//GEN-LAST:event_jBIDTextFieldBPMouseClicked

    private void jRNoTextFieldBPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRNoTextFieldBPMouseClicked
        // TODO add your handling code here:
        mouse2 = 1;
        mouse1 = 0;
        mouse3 = 0;
    }//GEN-LAST:event_jRNoTextFieldBPMouseClicked

    private void jAmountTextFieldBPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAmountTextFieldBPMouseClicked
        // TODO add your handling code here:
        mouse3 = 1;
        mouse2 = 0;
        mouse1 = 0;
    }//GEN-LAST:event_jAmountTextFieldBPMouseClicked

    private void jSubmitButtonBPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubmitButtonBPActionPerformed
        // TODO add your handling code here:

        String myline = "";
        String otherpart = "";
        try {
            FileReader fr = new FileReader("temp.txt");
            BufferedReader br = new BufferedReader(fr);
            String line;

            while ((line = br.readLine()) != null) {
                arr1 = line.split("#");
                if (arr1[0].equals(userName) && arr1[1].equals(pass)) {
                    myline = line;
                    df = Double.parseDouble(arr1[3]);
                    System.out.println(df);
                } else {
                    otherpart += line + "$";
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(CashWithdraw.class.getName()).log(Level.SEVERE, null, ex);
        }

        
        du = Double.parseDouble(number3);
        if (du <= df) {
            if (du <= 50000) {
                mr = mcw.submoney(df, du);
                cv = String.valueOf(mr);
                System.out.println(cv);

                String myarr[] = myline.split("#");
                myarr[3] = cv;
                myline = myarr[0] + "#" + myarr[1] + "#" + myarr[2] + "#" + myarr[3] + "#" + myarr[4] + "#" + myarr[5] + "$";

                otherpart += myline;

                try {

                    PrintWriter pw = new PrintWriter(new FileWriter("temp.txt"));

                    String linearr[] = otherpart.split("[$]");
                    for (int lineno = 0; lineno < linearr.length; lineno++) {
                        pw.write(linearr[lineno]);
                        pw.println();
                    }
                    pw.close();
                } catch (Exception e) {
                    e.printStackTrace();
                }

                String sourceFileName = "temp.txt";
                String destinationFileName = "login.txt";

                try {
                    BufferedReader br = new BufferedReader(new FileReader(sourceFileName));
                    PrintWriter pw = new PrintWriter(new FileWriter(destinationFileName));

                    String line;
                    while ((line = br.readLine()) != null) {
                        pw.write(line);
                        pw.println();
                    }

                    br.close();
                    pw.close();
                } catch (Exception e) {
                    e.printStackTrace();
                }
                
                mcw.history(userName, pass, "Bill Pay", du);
                JOptionPane.showMessageDialog(rootPane, "BIll Pay Successfull To\nBiller ID "+ number1);
                
            } else {
                JOptionPane.showMessageDialog(rootPane, "Bill Pay Amount Excedded.\nPlease Pay Less Then 50,000 BDT At A Time.");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Insufficient Amount.\nPlease Check Balance First.");
        }
    }//GEN-LAST:event_jSubmitButtonBPActionPerformed

    private void jBackButtonBpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBackButtonBpActionPerformed
        // TODO add your handling code here:
        Home h = new Home(userName, pass);
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBackButtonBpActionPerformed

    private void jLogOutButtonBPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLogOutButtonBPActionPerformed
        // TODO add your handling code here:
        lcw.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLogOutButtonBPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillPay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillPay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillPay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillPay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillPay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAmountLabelBp;
    private javax.swing.JTextField jAmountTextFieldBP;
    private javax.swing.JTextField jBIDTextFieldBP;
    private javax.swing.JButton jBackButtonBp;
    private javax.swing.JLabel jBackgroundLabelBP;
    private javax.swing.JLabel jBillPayLabelBP;
    private javax.swing.JLabel jBillerIdLabelBP;
    private javax.swing.JButton jButton0BP;
    private javax.swing.JButton jButton1BP;
    private javax.swing.JButton jButton2BP;
    private javax.swing.JButton jButton3BP;
    private javax.swing.JButton jButton4BP;
    private javax.swing.JButton jButton5BP;
    private javax.swing.JButton jButton6BP;
    private javax.swing.JButton jButton7BP;
    private javax.swing.JButton jButton8BP;
    private javax.swing.JButton jButton9BP;
    private javax.swing.JButton jClearBIDButtonBP;
    private javax.swing.JButton jClearMAButtonBP;
    private javax.swing.JButton jClearRNButtonBP;
    private javax.swing.JLabel jKeyBoardLabelBP;
    private javax.swing.JButton jLogOutButtonBP;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jRNoTextFieldBP;
    private javax.swing.JLabel jRefNoLabelBP;
    private javax.swing.JButton jSubmitButtonBP;
    // End of variables declaration//GEN-END:variables
}
