/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import static java.lang.System.exit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import static sun.security.jgss.GSSUtil.login;

/**
 *
 * @author Hebron Hossain Hamim
 */
public class CashWithdraw extends javax.swing.JFrame {

    /**
     * Creates new form CashWithdraw
     */
    private String userName;
    private String pass;
    String number, cv;
    LogIn lcw = new LogIn();
    Method mcw = new Method();
    String arr1[] = new String[40];
    double df, du, mr;

    public CashWithdraw(String userName, String pass) {
        this.userName = userName;
        this.pass = pass;
        initComponents();

        String sourceFileName = "login.txt";
        String destinationFileName = "temp.txt";

        try {
            BufferedReader br = new BufferedReader(new FileReader(sourceFileName));
            PrintWriter pw = new PrintWriter(new FileWriter(destinationFileName));

            String line;
            while ((line = br.readLine()) != null) {
                pw.write(line);
                pw.println();
            }

            br.close();
            pw.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public CashWithdraw() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jCashWithdrawLabelCW = new javax.swing.JLabel();
        jAmountLabelCW = new javax.swing.JLabel();
        jTextFieldCW = new javax.swing.JTextField();
        jSubmitButtonCW = new javax.swing.JButton();
        jClearButtonCW = new javax.swing.JButton();
        jBackButtonCW = new javax.swing.JButton();
        jLogOutButtonCW = new javax.swing.JButton();
        jButton1CW = new javax.swing.JButton();
        jButton2CW = new javax.swing.JButton();
        jButton3CW = new javax.swing.JButton();
        jButton4CW = new javax.swing.JButton();
        jButton5CW = new javax.swing.JButton();
        jButton6CW = new javax.swing.JButton();
        jButton7CW = new javax.swing.JButton();
        jButton8CW = new javax.swing.JButton();
        jButton9CW = new javax.swing.JButton();
        jButton0CW = new javax.swing.JButton();
        jKeyBoardLabelCW = new javax.swing.JLabel();
        jBackgroundLabelCW = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCashWithdrawLabelCW.setBackground(new java.awt.Color(255, 255, 255));
        jCashWithdrawLabelCW.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jCashWithdrawLabelCW.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jCashWithdrawLabelCW.setText("Cash Withdraw");
        jCashWithdrawLabelCW.setOpaque(true);
        jPanel1.add(jCashWithdrawLabelCW, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 650, 50));

        jAmountLabelCW.setBackground(new java.awt.Color(255, 255, 255));
        jAmountLabelCW.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jAmountLabelCW.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jAmountLabelCW.setText("Input Amount Of Money");
        jAmountLabelCW.setOpaque(true);
        jPanel1.add(jAmountLabelCW, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 250, 40));

        jTextFieldCW.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jTextFieldCW.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCW.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldCWMouseClicked(evt);
            }
        });
        jTextFieldCW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCWActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldCW, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 200, 40));

        jSubmitButtonCW.setBackground(new java.awt.Color(0, 153, 0));
        jSubmitButtonCW.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jSubmitButtonCW.setForeground(new java.awt.Color(255, 255, 255));
        jSubmitButtonCW.setText("Submit");
        jSubmitButtonCW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubmitButtonCWActionPerformed(evt);
            }
        });
        jPanel1.add(jSubmitButtonCW, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 190, 50));

        jClearButtonCW.setBackground(new java.awt.Color(0, 0, 0));
        jClearButtonCW.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jClearButtonCW.setForeground(new java.awt.Color(255, 255, 255));
        jClearButtonCW.setText("Clear");
        jClearButtonCW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClearButtonCWActionPerformed(evt);
            }
        });
        jPanel1.add(jClearButtonCW, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, 70, 40));

        jBackButtonCW.setBackground(new java.awt.Color(0, 0, 0));
        jBackButtonCW.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jBackButtonCW.setForeground(new java.awt.Color(255, 255, 255));
        jBackButtonCW.setText("Back");
        jBackButtonCW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBackButtonCWActionPerformed(evt);
            }
        });
        jPanel1.add(jBackButtonCW, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, 190, 50));

        jLogOutButtonCW.setBackground(new java.awt.Color(255, 0, 0));
        jLogOutButtonCW.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLogOutButtonCW.setForeground(new java.awt.Color(255, 255, 255));
        jLogOutButtonCW.setText("Log Out");
        jLogOutButtonCW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogOutButtonCWActionPerformed(evt);
            }
        });
        jPanel1.add(jLogOutButtonCW, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 490, 190, 50));

        jButton1CW.setBackground(new java.awt.Color(0, 0, 0));
        jButton1CW.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jButton1CW.setForeground(new java.awt.Color(255, 255, 255));
        jButton1CW.setText("1");
        jButton1CW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1CWActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1CW, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 60, 40));

        jButton2CW.setBackground(new java.awt.Color(0, 0, 0));
        jButton2CW.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jButton2CW.setForeground(new java.awt.Color(255, 255, 255));
        jButton2CW.setText("2");
        jButton2CW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2CWActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2CW, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 60, 40));

        jButton3CW.setBackground(new java.awt.Color(0, 0, 0));
        jButton3CW.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jButton3CW.setForeground(new java.awt.Color(255, 255, 255));
        jButton3CW.setText("3");
        jButton3CW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3CWActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3CW, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 60, 40));

        jButton4CW.setBackground(new java.awt.Color(0, 0, 0));
        jButton4CW.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jButton4CW.setForeground(new java.awt.Color(255, 255, 255));
        jButton4CW.setText("4");
        jButton4CW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4CWActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4CW, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 60, 40));

        jButton5CW.setBackground(new java.awt.Color(0, 0, 0));
        jButton5CW.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jButton5CW.setForeground(new java.awt.Color(255, 255, 255));
        jButton5CW.setText("5");
        jButton5CW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5CWActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5CW, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 60, 40));

        jButton6CW.setBackground(new java.awt.Color(0, 0, 0));
        jButton6CW.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jButton6CW.setForeground(new java.awt.Color(255, 255, 255));
        jButton6CW.setText("6");
        jButton6CW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6CWActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6CW, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 60, 40));

        jButton7CW.setBackground(new java.awt.Color(0, 0, 0));
        jButton7CW.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jButton7CW.setForeground(new java.awt.Color(255, 255, 255));
        jButton7CW.setText("7");
        jButton7CW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7CWActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7CW, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 60, 40));

        jButton8CW.setBackground(new java.awt.Color(0, 0, 0));
        jButton8CW.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jButton8CW.setForeground(new java.awt.Color(255, 255, 255));
        jButton8CW.setText("8");
        jButton8CW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8CWActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8CW, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, 60, 40));

        jButton9CW.setBackground(new java.awt.Color(0, 0, 0));
        jButton9CW.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jButton9CW.setForeground(new java.awt.Color(255, 255, 255));
        jButton9CW.setText("9");
        jButton9CW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9CWActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9CW, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, 60, 40));

        jButton0CW.setBackground(new java.awt.Color(0, 0, 0));
        jButton0CW.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jButton0CW.setForeground(new java.awt.Color(255, 255, 255));
        jButton0CW.setText("0");
        jButton0CW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton0CWActionPerformed(evt);
            }
        });
        jPanel1.add(jButton0CW, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 490, 60, 40));

        jKeyBoardLabelCW.setBackground(new java.awt.Color(255, 255, 255));
        jKeyBoardLabelCW.setOpaque(true);
        jPanel1.add(jKeyBoardLabelCW, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 340, 180));

        jBackgroundLabelCW.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hebron Hossain Hamim\\Desktop\\ATM Project\\Images\\bnwb.jpg")); // NOI18N
        jPanel1.add(jBackgroundLabelCW, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCWActionPerformed

    private void jButton1CWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1CWActionPerformed
        // TODO add your handling code here:
        number = jTextFieldCW.getText() + "1";
        jTextFieldCW.setText(number);
    }//GEN-LAST:event_jButton1CWActionPerformed

    private void jLogOutButtonCWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLogOutButtonCWActionPerformed
        // TODO add your handling code here:
        lcw.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLogOutButtonCWActionPerformed

    private void jButton2CWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2CWActionPerformed
        // TODO add your handling code here:
        number = jTextFieldCW.getText() + "2";
        jTextFieldCW.setText(number);
    }//GEN-LAST:event_jButton2CWActionPerformed

    private void jButton3CWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3CWActionPerformed
        // TODO add your handling code here:
        number = jTextFieldCW.getText() + "3";
        jTextFieldCW.setText(number);
    }//GEN-LAST:event_jButton3CWActionPerformed

    private void jButton4CWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4CWActionPerformed
        // TODO add your handling code here:
        number = jTextFieldCW.getText() + "4";
        jTextFieldCW.setText(number);
    }//GEN-LAST:event_jButton4CWActionPerformed

    private void jButton5CWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5CWActionPerformed
        // TODO add your handling code here:
        number = jTextFieldCW.getText() + "5";
        jTextFieldCW.setText(number);
    }//GEN-LAST:event_jButton5CWActionPerformed

    private void jButton6CWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6CWActionPerformed
        // TODO add your handling code here:
        number = jTextFieldCW.getText() + "6";
        jTextFieldCW.setText(number);
    }//GEN-LAST:event_jButton6CWActionPerformed

    private void jButton7CWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7CWActionPerformed
        // TODO add your handling code here:
        number = jTextFieldCW.getText() + "7";
        jTextFieldCW.setText(number);
    }//GEN-LAST:event_jButton7CWActionPerformed

    private void jButton8CWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8CWActionPerformed
        // TODO add your handling code here:
        number = jTextFieldCW.getText() + "8";
        jTextFieldCW.setText(number);
    }//GEN-LAST:event_jButton8CWActionPerformed

    private void jButton9CWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9CWActionPerformed
        // TODO add your handling code here:
        number = jTextFieldCW.getText() + "9";
        jTextFieldCW.setText(number);
    }//GEN-LAST:event_jButton9CWActionPerformed

    private void jButton0CWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton0CWActionPerformed
        // TODO add your handling code here:
        number = jTextFieldCW.getText() + "0";
        jTextFieldCW.setText(number);
    }//GEN-LAST:event_jButton0CWActionPerformed

    private void jTextFieldCWMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldCWMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCWMouseClicked

    private void jSubmitButtonCWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubmitButtonCWActionPerformed
        // TODO add your handling code here:

        String myline = "";
        String otherpart = "";
        try {
            FileReader fr = new FileReader("temp.txt");
            BufferedReader br = new BufferedReader(fr);
            String line;

            while ((line = br.readLine()) != null) {
                arr1 = line.split("#");
                if (arr1[0].equals(userName) && arr1[1].equals(pass)) {
                    myline = line;
                    df = Double.parseDouble(arr1[3]);
                    System.out.println(df);
                } else {
                    otherpart += line + "$";
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(CashWithdraw.class.getName()).log(Level.SEVERE, null, ex);
        }

        du = Double.parseDouble(number);

        if (du <= df) {
            if (du <= 50000) {
                mr = mcw.submoney(df, du);
                cv = String.valueOf(mr);
                System.out.println(cv);

                String myarr[] = myline.split("#");
                myarr[3] = cv;
                myline = myarr[0] + "#" + myarr[1] + "#" + myarr[2] + "#" + myarr[3] + "#" + myarr[4] + "#" + myarr[5] + "$";

                otherpart += myline;

                try {

                    PrintWriter pw = new PrintWriter(new FileWriter("temp.txt"));

                    String linearr[] = otherpart.split("[$]");
                    for (int lineno = 0; lineno < linearr.length; lineno++) {
                        pw.write(linearr[lineno]);
                        pw.println();
                    }
                    pw.close();
                } catch (Exception e) {
                    e.printStackTrace();
                }

                String sourceFileName = "temp.txt";
                String destinationFileName = "login.txt";

                try {
                    BufferedReader br = new BufferedReader(new FileReader(sourceFileName));
                    PrintWriter pw = new PrintWriter(new FileWriter(destinationFileName));

                    String line;
                    while ((line = br.readLine()) != null) {
                        pw.write(line);
                        pw.println();
                    }

                    br.close();
                    pw.close();
                } catch (Exception e) {
                    e.printStackTrace();
                }
                
                mcw.history(userName, pass, "Cash Withdraw", du);
                JOptionPane.showMessageDialog(rootPane, "Cash Withdraw Successfull!!");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Withdrawal Amount Excedded.\nPlease Withdraw Less Than 50,000 BDT At A Time.");
            }

        } else {
            JOptionPane.showMessageDialog(rootPane, "Insufficient Amount.\nPlease Check Balance First.");
        }  
    }//GEN-LAST:event_jSubmitButtonCWActionPerformed

    private void jClearButtonCWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClearButtonCWActionPerformed
        // TODO add your handling code here:
        jTextFieldCW.setText("");
        number = "";
    }//GEN-LAST:event_jClearButtonCWActionPerformed

    private void jBackButtonCWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBackButtonCWActionPerformed
        // TODO add your handling code here:
        Home h = new Home(userName, pass);
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBackButtonCWActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashWithdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashWithdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashWithdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashWithdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new CashWithdraw().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAmountLabelCW;
    private javax.swing.JButton jBackButtonCW;
    private javax.swing.JLabel jBackgroundLabelCW;
    private javax.swing.JButton jButton0CW;
    private javax.swing.JButton jButton1CW;
    private javax.swing.JButton jButton2CW;
    private javax.swing.JButton jButton3CW;
    private javax.swing.JButton jButton4CW;
    private javax.swing.JButton jButton5CW;
    private javax.swing.JButton jButton6CW;
    private javax.swing.JButton jButton7CW;
    private javax.swing.JButton jButton8CW;
    private javax.swing.JButton jButton9CW;
    private javax.swing.JLabel jCashWithdrawLabelCW;
    private javax.swing.JButton jClearButtonCW;
    private javax.swing.JLabel jKeyBoardLabelCW;
    private javax.swing.JButton jLogOutButtonCW;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jSubmitButtonCW;
    private javax.swing.JTextField jTextFieldCW;
    // End of variables declaration//GEN-END:variables
}
