/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import static java.lang.System.exit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Hebron Hossain Hamim
 */
public class FundTransfer extends javax.swing.JFrame {

    /**
     * Creates new form FundTransfer
     */
    private String userName;
    private String pass;
    String number1, number2, cv;
    LogIn lcw = new LogIn();
    Method mcw = new Method();
    String arr1[] = new String[40];
    double df, du, mr;
    int mouse1, mouse2, mouse3;

    public FundTransfer(String userName, String pass) {
        this.userName = userName;
        this.pass = pass;
        initComponents();


        String sourceFileName = "login.txt";
        String destinationFileName = "temp.txt";

        try {
            BufferedReader br = new BufferedReader(new FileReader(sourceFileName));
            PrintWriter pw = new PrintWriter(new FileWriter(destinationFileName));

            String line;
            while ((line = br.readLine()) != null) {
                pw.write(line);
                pw.println();
            }

            br.close();
            pw.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public FundTransfer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jFundTransferLabelFT = new javax.swing.JLabel();
        jBankNameLabelFT = new javax.swing.JLabel();
        jAccNoLabelFT = new javax.swing.JLabel();
        jAmountLabelFt = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jANTextFieldFT = new javax.swing.JTextField();
        jATextFieldFT = new javax.swing.JTextField();
        jClearANButtonFT = new javax.swing.JButton();
        jClearAButtonFt = new javax.swing.JButton();
        jSubmitButtonFT = new javax.swing.JButton();
        jBackButtonFT = new javax.swing.JButton();
        jLogoutButtonFT = new javax.swing.JButton();
        jButton1FT = new javax.swing.JButton();
        jButton2FT = new javax.swing.JButton();
        jButton3FT = new javax.swing.JButton();
        jButton4FT = new javax.swing.JButton();
        jButton5FT = new javax.swing.JButton();
        jButton6FT = new javax.swing.JButton();
        jButton7FT = new javax.swing.JButton();
        jButton8FT = new javax.swing.JButton();
        jButton9FT = new javax.swing.JButton();
        jButton0FT = new javax.swing.JButton();
        jKeyBoardLabelFT = new javax.swing.JLabel();
        jBackgroundLabelFT = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jFundTransferLabelFT.setBackground(new java.awt.Color(255, 255, 255));
        jFundTransferLabelFT.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jFundTransferLabelFT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jFundTransferLabelFT.setText("Fund Transfer");
        jFundTransferLabelFT.setOpaque(true);
        jPanel1.add(jFundTransferLabelFT, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 650, 50));

        jBankNameLabelFT.setBackground(new java.awt.Color(255, 255, 255));
        jBankNameLabelFT.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jBankNameLabelFT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jBankNameLabelFT.setText("Bank Name");
        jBankNameLabelFT.setOpaque(true);
        jPanel1.add(jBankNameLabelFT, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 250, 40));

        jAccNoLabelFT.setBackground(new java.awt.Color(255, 255, 255));
        jAccNoLabelFT.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jAccNoLabelFT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jAccNoLabelFT.setText("Account Number");
        jAccNoLabelFT.setOpaque(true);
        jPanel1.add(jAccNoLabelFT, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 250, 40));

        jAmountLabelFt.setBackground(new java.awt.Color(255, 255, 255));
        jAmountLabelFt.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jAmountLabelFt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jAmountLabelFt.setText("Input Amount");
        jAmountLabelFt.setOpaque(true);
        jPanel1.add(jAmountLabelFt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 250, 40));

        jComboBox2.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Bank", "Islami Bank Bangladesh Limited", "Sonali Bank Limited", "Janata Bank Limited", "BRAC Bank Limited", "Dhaka Bank Limited", "Dutch-Bangla Bank Limited", "Mutual Trust Bank Limited", "National Bank Limited", "Shimanto Bank Ltd", "Trust Bank Limited", "United Commercial Bank Limited" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 250, 40));

        jANTextFieldFT.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jANTextFieldFT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jANTextFieldFT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jANTextFieldFTMouseClicked(evt);
            }
        });
        jANTextFieldFT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jANTextFieldFTActionPerformed(evt);
            }
        });
        jPanel1.add(jANTextFieldFT, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 200, 40));

        jATextFieldFT.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jATextFieldFT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jATextFieldFT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jATextFieldFTMouseClicked(evt);
            }
        });
        jATextFieldFT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jATextFieldFTActionPerformed(evt);
            }
        });
        jPanel1.add(jATextFieldFT, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 200, 40));

        jClearANButtonFT.setBackground(new java.awt.Color(0, 0, 0));
        jClearANButtonFT.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jClearANButtonFT.setForeground(new java.awt.Color(255, 255, 255));
        jClearANButtonFT.setText("Clear");
        jClearANButtonFT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClearANButtonFTActionPerformed(evt);
            }
        });
        jPanel1.add(jClearANButtonFT, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, 70, 40));

        jClearAButtonFt.setBackground(new java.awt.Color(0, 0, 0));
        jClearAButtonFt.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jClearAButtonFt.setForeground(new java.awt.Color(255, 255, 255));
        jClearAButtonFt.setText("Clear");
        jClearAButtonFt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClearAButtonFtActionPerformed(evt);
            }
        });
        jPanel1.add(jClearAButtonFt, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, 70, 40));

        jSubmitButtonFT.setBackground(new java.awt.Color(0, 153, 0));
        jSubmitButtonFT.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jSubmitButtonFT.setForeground(new java.awt.Color(255, 255, 255));
        jSubmitButtonFT.setText("Submit");
        jSubmitButtonFT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubmitButtonFTActionPerformed(evt);
            }
        });
        jPanel1.add(jSubmitButtonFT, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 190, 50));

        jBackButtonFT.setBackground(new java.awt.Color(0, 0, 0));
        jBackButtonFT.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jBackButtonFT.setForeground(new java.awt.Color(255, 255, 255));
        jBackButtonFT.setText("Back");
        jBackButtonFT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBackButtonFTActionPerformed(evt);
            }
        });
        jPanel1.add(jBackButtonFT, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, 190, 50));

        jLogoutButtonFT.setBackground(new java.awt.Color(255, 0, 0));
        jLogoutButtonFT.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLogoutButtonFT.setForeground(new java.awt.Color(255, 255, 255));
        jLogoutButtonFT.setText("Log Out");
        jLogoutButtonFT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogoutButtonFTActionPerformed(evt);
            }
        });
        jPanel1.add(jLogoutButtonFT, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 490, 190, 50));

        jButton1FT.setBackground(new java.awt.Color(0, 0, 0));
        jButton1FT.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jButton1FT.setForeground(new java.awt.Color(255, 255, 255));
        jButton1FT.setText("1");
        jButton1FT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1FTActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1FT, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 60, 40));

        jButton2FT.setBackground(new java.awt.Color(0, 0, 0));
        jButton2FT.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jButton2FT.setForeground(new java.awt.Color(255, 255, 255));
        jButton2FT.setText("2");
        jButton2FT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2FTActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2FT, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 60, 40));

        jButton3FT.setBackground(new java.awt.Color(0, 0, 0));
        jButton3FT.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jButton3FT.setForeground(new java.awt.Color(255, 255, 255));
        jButton3FT.setText("3");
        jButton3FT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3FTActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3FT, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 60, 40));

        jButton4FT.setBackground(new java.awt.Color(0, 0, 0));
        jButton4FT.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jButton4FT.setForeground(new java.awt.Color(255, 255, 255));
        jButton4FT.setText("4");
        jButton4FT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4FTActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4FT, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 60, 40));

        jButton5FT.setBackground(new java.awt.Color(0, 0, 0));
        jButton5FT.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jButton5FT.setForeground(new java.awt.Color(255, 255, 255));
        jButton5FT.setText("5");
        jButton5FT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5FTActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5FT, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 60, 40));

        jButton6FT.setBackground(new java.awt.Color(0, 0, 0));
        jButton6FT.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jButton6FT.setForeground(new java.awt.Color(255, 255, 255));
        jButton6FT.setText("6");
        jButton6FT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6FTActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6FT, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 60, 40));

        jButton7FT.setBackground(new java.awt.Color(0, 0, 0));
        jButton7FT.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jButton7FT.setForeground(new java.awt.Color(255, 255, 255));
        jButton7FT.setText("7");
        jButton7FT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7FTActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7FT, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 60, 40));

        jButton8FT.setBackground(new java.awt.Color(0, 0, 0));
        jButton8FT.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jButton8FT.setForeground(new java.awt.Color(255, 255, 255));
        jButton8FT.setText("8");
        jButton8FT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8FTActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8FT, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, 60, 40));

        jButton9FT.setBackground(new java.awt.Color(0, 0, 0));
        jButton9FT.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jButton9FT.setForeground(new java.awt.Color(255, 255, 255));
        jButton9FT.setText("9");
        jButton9FT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9FTActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9FT, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, 60, 40));

        jButton0FT.setBackground(new java.awt.Color(0, 0, 0));
        jButton0FT.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jButton0FT.setForeground(new java.awt.Color(255, 255, 255));
        jButton0FT.setText("0");
        jButton0FT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton0FTActionPerformed(evt);
            }
        });
        jPanel1.add(jButton0FT, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 490, 60, 40));

        jKeyBoardLabelFT.setBackground(new java.awt.Color(255, 255, 255));
        jKeyBoardLabelFT.setOpaque(true);
        jPanel1.add(jKeyBoardLabelFT, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 340, 180));

        jBackgroundLabelFT.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hebron Hossain Hamim\\Desktop\\ATM Project\\Images\\bnwb.jpg")); // NOI18N
        jPanel1.add(jBackgroundLabelFT, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1FTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1FTActionPerformed
        // TODO add your handling code here:
        if (mouse1 >= 1) {
            number1 = jANTextFieldFT.getText() + "1";
            jANTextFieldFT.setText(number1);
        } else if (mouse2 >= 1) {
            number2 = jATextFieldFT.getText() + "1";
            jATextFieldFT.setText(number2);
        }
    }//GEN-LAST:event_jButton1FTActionPerformed

    private void jButton2FTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2FTActionPerformed
        // TODO add your handling code here:
        if (mouse1 >= 1) {
            number1 = jANTextFieldFT.getText() + "2";
            jANTextFieldFT.setText(number1);
        } else if (mouse2 >= 1) {
            number2 = jATextFieldFT.getText() + "2";
            jATextFieldFT.setText(number2);
        }
    }//GEN-LAST:event_jButton2FTActionPerformed

    private void jButton3FTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3FTActionPerformed
        // TODO add your handling code here:
        if (mouse1 >= 1) {
            number1 = jANTextFieldFT.getText() + "3";
            jANTextFieldFT.setText(number1);
        } else if (mouse2 >= 1) {
            number2 = jATextFieldFT.getText() + "3";
            jATextFieldFT.setText(number2);
        }
    }//GEN-LAST:event_jButton3FTActionPerformed

    private void jButton4FTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4FTActionPerformed
        // TODO add your handling code here:
        if (mouse1 >= 1) {
            number1 = jANTextFieldFT.getText() + "4";
            jANTextFieldFT.setText(number1);
        } else if (mouse2 >= 1) {
            number2 = jATextFieldFT.getText() + "4";
            jATextFieldFT.setText(number2);
        }
    }//GEN-LAST:event_jButton4FTActionPerformed

    private void jButton5FTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5FTActionPerformed
        // TODO add your handling code here:
        if (mouse1 >= 1) {
            number1 = jANTextFieldFT.getText() + "5";
            jANTextFieldFT.setText(number1);
        } else if (mouse2 >= 1) {
            number2 = jATextFieldFT.getText() + "5";
            jATextFieldFT.setText(number2);
        }
    }//GEN-LAST:event_jButton5FTActionPerformed

    private void jButton6FTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6FTActionPerformed
        // TODO add your handling code here:
        if (mouse1 >= 1) {
            number1 = jANTextFieldFT.getText() + "6";
            jANTextFieldFT.setText(number1);
        } else if (mouse2 >= 1) {
            number2 = jATextFieldFT.getText() + "6";
            jATextFieldFT.setText(number2);
        }
    }//GEN-LAST:event_jButton6FTActionPerformed

    private void jButton7FTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7FTActionPerformed
        // TODO add your handling code here:
        if (mouse1 >= 1) {
            number1 = jANTextFieldFT.getText() + "7";
            jANTextFieldFT.setText(number1);
        } else if (mouse2 >= 1) {
            number2 = jATextFieldFT.getText() + "7";
            jATextFieldFT.setText(number2);
        }
    }//GEN-LAST:event_jButton7FTActionPerformed

    private void jButton8FTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8FTActionPerformed
        // TODO add your handling code here:
        if (mouse1 >= 1) {
            number1 = jANTextFieldFT.getText() + "8";
            jANTextFieldFT.setText(number1);
        } else if (mouse2 >= 1) {
            number2 = jATextFieldFT.getText() + "8";
            jATextFieldFT.setText(number2);
        }
    }//GEN-LAST:event_jButton8FTActionPerformed

    private void jButton9FTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9FTActionPerformed
        // TODO add your handling code here:
        if (mouse1 >= 1) {
            number1 = jANTextFieldFT.getText() + "9";
            jANTextFieldFT.setText(number1);
        } else if (mouse2 >= 1) {
            number2 = jATextFieldFT.getText() + "9";
            jATextFieldFT.setText(number2);
        }
    }//GEN-LAST:event_jButton9FTActionPerformed

    private void jButton0FTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton0FTActionPerformed
        // TODO add your handling code here:
        if (mouse1 >= 1) {
            number1 = jANTextFieldFT.getText() + "0";
            jANTextFieldFT.setText(number1);
        } else if (mouse2 >= 1) {
            number2 = jATextFieldFT.getText() + "0";
            jATextFieldFT.setText(number2);
        }
    }//GEN-LAST:event_jButton0FTActionPerformed

    private void jBackButtonFTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBackButtonFTActionPerformed
        // TODO add your handling code here:
        Home h = new Home(userName, pass);
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBackButtonFTActionPerformed

    private void jLogoutButtonFTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLogoutButtonFTActionPerformed
        // TODO add your handling code here:
        lcw.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLogoutButtonFTActionPerformed

    private void jClearANButtonFTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClearANButtonFTActionPerformed
        // TODO add your handling code here:
        jANTextFieldFT.setText("");
        number1 = "";
    }//GEN-LAST:event_jClearANButtonFTActionPerformed

    private void jClearAButtonFtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClearAButtonFtActionPerformed
        // TODO add your handling code here:
        jATextFieldFT.setText("");
        number2 = "";
    }//GEN-LAST:event_jClearAButtonFtActionPerformed

    private void jSubmitButtonFTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubmitButtonFTActionPerformed
        // TODO add your handling code here:

        String myline = "";
        String otherpart = "";
        try {
            FileReader fr = new FileReader("temp.txt");
            BufferedReader br = new BufferedReader(fr);
            String line;

            while ((line = br.readLine()) != null) {
                arr1 = line.split("#");
                if (arr1[0].equals(userName) && arr1[1].equals(pass)) {
                    myline = line;
                    df = Double.parseDouble(arr1[3]);
                    System.out.println(df);
                } else {
                    otherpart += line + "$";
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(CashWithdraw.class.getName()).log(Level.SEVERE, null, ex);
        }

        du = Double.parseDouble(number2);
        if (du <= df) {
            if (du <= 500000) {
                mr = mcw.submoney(df, du);
                cv = String.valueOf(mr);
                System.out.println(cv);

                String myarr[] = myline.split("#");
                myarr[3] = cv;
                myline = myarr[0] + "#" + myarr[1] + "#" + myarr[2] + "#" + myarr[3] + "#" + myarr[4] + "#" + myarr[5] + "$";

                otherpart += myline;

                try {

                    PrintWriter pw = new PrintWriter(new FileWriter("temp.txt"));

                    String linearr[] = otherpart.split("[$]");
                    for (int lineno = 0; lineno < linearr.length; lineno++) {
                        pw.write(linearr[lineno]);
                        pw.println();
                    }
                    pw.close();
                } catch (Exception e) {
                    e.printStackTrace();
                }

                String sourceFileName = "temp.txt";
                String destinationFileName = "login.txt";

                try {
                    BufferedReader br = new BufferedReader(new FileReader(sourceFileName));
                    PrintWriter pw = new PrintWriter(new FileWriter(destinationFileName));

                    String line;
                    while ((line = br.readLine()) != null) {
                        pw.write(line);
                        pw.println();
                    }

                    br.close();
                    pw.close();
                } catch (Exception e) {
                    e.printStackTrace();
                }
                
                mcw.history(userName, pass, "Fund Tranfer", du);
                JOptionPane.showMessageDialog(rootPane, "Fund Transfer Successfull To Account number "+number1);

            } else {
                JOptionPane.showMessageDialog(rootPane, "Transferred Amount Excedded.\nPlease Transfer Less Then 5 Lakh BDT At A Time.");
            }

        } else {
            JOptionPane.showMessageDialog(rootPane, "InSufficiant Balance.\nPlease Check Balance First.");
        }
    }//GEN-LAST:event_jSubmitButtonFTActionPerformed

    private void jANTextFieldFTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jANTextFieldFTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jANTextFieldFTActionPerformed

    private void jATextFieldFTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jATextFieldFTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jATextFieldFTActionPerformed

    private void jANTextFieldFTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jANTextFieldFTMouseClicked
        // TODO add your handling code here:
        mouse1 = 1;
        mouse2 = 0;
    }//GEN-LAST:event_jANTextFieldFTMouseClicked

    private void jATextFieldFTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jATextFieldFTMouseClicked
        // TODO add your handling code here:
        mouse1 = 0;
        mouse2 = 1;
    }//GEN-LAST:event_jATextFieldFTMouseClicked

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FundTransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FundTransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FundTransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FundTransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FundTransfer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jANTextFieldFT;
    private javax.swing.JTextField jATextFieldFT;
    private javax.swing.JLabel jAccNoLabelFT;
    private javax.swing.JLabel jAmountLabelFt;
    private javax.swing.JButton jBackButtonFT;
    private javax.swing.JLabel jBackgroundLabelFT;
    private javax.swing.JLabel jBankNameLabelFT;
    private javax.swing.JButton jButton0FT;
    private javax.swing.JButton jButton1FT;
    private javax.swing.JButton jButton2FT;
    private javax.swing.JButton jButton3FT;
    private javax.swing.JButton jButton4FT;
    private javax.swing.JButton jButton5FT;
    private javax.swing.JButton jButton6FT;
    private javax.swing.JButton jButton7FT;
    private javax.swing.JButton jButton8FT;
    private javax.swing.JButton jButton9FT;
    private javax.swing.JButton jClearAButtonFt;
    private javax.swing.JButton jClearANButtonFT;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jFundTransferLabelFT;
    private javax.swing.JLabel jKeyBoardLabelFT;
    private javax.swing.JButton jLogoutButtonFT;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jSubmitButtonFT;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
