/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import static java.lang.System.exit;
import javax.swing.JOptionPane;

/**
 *
 * @author Hebron Hossain Hamim
 */
public class Home extends javax.swing.JFrame {
    
    LogIn lcw = new LogIn();
    private  String userName;
    private  String pass;
    /** Creates new form Home */
    public Home() {
        initComponents();
    }
    
    public Home(String userName, String pass) {
        this.userName = userName;
        this.pass = pass;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBackgroundPanelH = new javax.swing.JPanel();
        jHomeLabelH = new javax.swing.JLabel();
        jCWButtonH = new javax.swing.JButton();
        jBCButtonH = new javax.swing.JButton();
        jSButtonH = new javax.swing.JButton();
        jPCButtonH = new javax.swing.JButton();
        jCDButtonH = new javax.swing.JButton();
        jBPButtonH = new javax.swing.JButton();
        jFTButtonH = new javax.swing.JButton();
        jTUButtonH = new javax.swing.JButton();
        jLOButtonH = new javax.swing.JButton();
        jBackgroundLabelH = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jBackgroundPanelH.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jHomeLabelH.setBackground(new java.awt.Color(255, 255, 255));
        jHomeLabelH.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jHomeLabelH.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jHomeLabelH.setText("HOME");
        jHomeLabelH.setOpaque(true);
        jBackgroundPanelH.add(jHomeLabelH, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 650, 50));

        jCWButtonH.setBackground(new java.awt.Color(0, 0, 0));
        jCWButtonH.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jCWButtonH.setForeground(new java.awt.Color(255, 255, 255));
        jCWButtonH.setText("Cash Withdraw");
        jCWButtonH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCWButtonHActionPerformed(evt);
            }
        });
        jBackgroundPanelH.add(jCWButtonH, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 190, 50));

        jBCButtonH.setBackground(new java.awt.Color(0, 0, 0));
        jBCButtonH.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jBCButtonH.setForeground(new java.awt.Color(255, 255, 255));
        jBCButtonH.setText("Balance Check");
        jBCButtonH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCButtonHActionPerformed(evt);
            }
        });
        jBackgroundPanelH.add(jBCButtonH, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 190, 50));

        jSButtonH.setBackground(new java.awt.Color(0, 0, 0));
        jSButtonH.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jSButtonH.setForeground(new java.awt.Color(255, 255, 255));
        jSButtonH.setText("Statement");
        jSButtonH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSButtonHActionPerformed(evt);
            }
        });
        jBackgroundPanelH.add(jSButtonH, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 190, 50));

        jPCButtonH.setBackground(new java.awt.Color(0, 0, 0));
        jPCButtonH.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jPCButtonH.setForeground(new java.awt.Color(255, 255, 255));
        jPCButtonH.setText("Pin Change");
        jPCButtonH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPCButtonHActionPerformed(evt);
            }
        });
        jBackgroundPanelH.add(jPCButtonH, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 190, 50));

        jCDButtonH.setBackground(new java.awt.Color(0, 0, 0));
        jCDButtonH.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jCDButtonH.setForeground(new java.awt.Color(255, 255, 255));
        jCDButtonH.setText("Cash Deposit");
        jCDButtonH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCDButtonHActionPerformed(evt);
            }
        });
        jBackgroundPanelH.add(jCDButtonH, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 190, 50));

        jBPButtonH.setBackground(new java.awt.Color(0, 0, 0));
        jBPButtonH.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jBPButtonH.setForeground(new java.awt.Color(255, 255, 255));
        jBPButtonH.setText("Bill Pay");
        jBPButtonH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPButtonHActionPerformed(evt);
            }
        });
        jBackgroundPanelH.add(jBPButtonH, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 190, 50));

        jFTButtonH.setBackground(new java.awt.Color(0, 0, 0));
        jFTButtonH.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jFTButtonH.setForeground(new java.awt.Color(255, 255, 255));
        jFTButtonH.setText("Fund Transfer");
        jFTButtonH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFTButtonHActionPerformed(evt);
            }
        });
        jBackgroundPanelH.add(jFTButtonH, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, 190, 50));

        jTUButtonH.setBackground(new java.awt.Color(0, 0, 0));
        jTUButtonH.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jTUButtonH.setForeground(new java.awt.Color(255, 255, 255));
        jTUButtonH.setText("Top Up");
        jTUButtonH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTUButtonHActionPerformed(evt);
            }
        });
        jBackgroundPanelH.add(jTUButtonH, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, 190, 50));

        jLOButtonH.setBackground(new java.awt.Color(255, 0, 0));
        jLOButtonH.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLOButtonH.setForeground(new java.awt.Color(255, 255, 255));
        jLOButtonH.setText("Log Out");
        jLOButtonH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLOButtonHActionPerformed(evt);
            }
        });
        jBackgroundPanelH.add(jLOButtonH, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, 190, 50));

        jBackgroundLabelH.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hebron Hossain Hamim\\Desktop\\ATM Project\\Images\\bnwb.jpg")); // NOI18N
        jBackgroundPanelH.add(jBackgroundLabelH, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBackgroundPanelH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBackgroundPanelH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPCButtonHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPCButtonHActionPerformed
        // TODO add your handling code here:
        PinChange pc = new PinChange(userName,pass);
        pc.setVisible(true);
    }//GEN-LAST:event_jPCButtonHActionPerformed

    private void jCDButtonHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCDButtonHActionPerformed
        // TODO add your handling code here:
        CashDeposit cd = new CashDeposit(userName,pass);
        cd.setVisible(true);
    }//GEN-LAST:event_jCDButtonHActionPerformed

    private void jLOButtonHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLOButtonHActionPerformed
        // TODO add your handling code here:
        lcw.setVisible(true);
    }//GEN-LAST:event_jLOButtonHActionPerformed

    private void jCWButtonHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCWButtonHActionPerformed
        // TODO add your handling code here:
        CashWithdraw cw = new CashWithdraw(userName,pass);
        cw.setVisible(true);
        
    }//GEN-LAST:event_jCWButtonHActionPerformed

    private void jBCButtonHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCButtonHActionPerformed
        // TODO add your handling code here:
        BalanceCheck bc  = new BalanceCheck(userName,pass);
        bc.setVisible(true);
    }//GEN-LAST:event_jBCButtonHActionPerformed

    private void jBPButtonHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPButtonHActionPerformed
        // TODO add your handling code here:
        BillPay bp = new BillPay(userName,pass);
        bp.setVisible(true);
    }//GEN-LAST:event_jBPButtonHActionPerformed

    private void jSButtonHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSButtonHActionPerformed
        // TODO add your handling code here:
        Statement s = new Statement(userName,pass);
        s.setVisible(true);
    }//GEN-LAST:event_jSButtonHActionPerformed

    private void jFTButtonHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFTButtonHActionPerformed
        // TODO add your handling code here:
        FundTransfer ft = new FundTransfer(userName,pass);
        ft.setVisible(true);
    }//GEN-LAST:event_jFTButtonHActionPerformed

    private void jTUButtonHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTUButtonHActionPerformed
        // TODO add your handling code here:
        MobileTopUp tu = new MobileTopUp(userName,pass);
        tu.setVisible(true);
    }//GEN-LAST:event_jTUButtonHActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCButtonH;
    private javax.swing.JButton jBPButtonH;
    private javax.swing.JLabel jBackgroundLabelH;
    private javax.swing.JPanel jBackgroundPanelH;
    private javax.swing.JButton jCDButtonH;
    private javax.swing.JButton jCWButtonH;
    private javax.swing.JButton jFTButtonH;
    private javax.swing.JLabel jHomeLabelH;
    private javax.swing.JButton jLOButtonH;
    private javax.swing.JButton jPCButtonH;
    private javax.swing.JButton jSButtonH;
    private javax.swing.JButton jTUButtonH;
    // End of variables declaration//GEN-END:variables

}
