/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Hebron Hossain Hamim
 */
public class MobileTopUp extends javax.swing.JFrame {

    /**
     * Creates new form MobileTopUp
     */
    private String userName;
    private String pass;
    String number1, number2, number3, cv;
    LogIn lcw = new LogIn();
    Method mcw = new Method();
    String arr1[] = new String[40];
    double df, du, mr;
    int mouse1, mouse2, mouse3;

    public MobileTopUp(String userName, String pass) {
        this.userName = userName;
        this.pass = pass;
        initComponents();

        String sourceFileName = "login.txt";
        String destinationFileName = "temp.txt";

        try {
            BufferedReader br = new BufferedReader(new FileReader(sourceFileName));
            PrintWriter pw = new PrintWriter(new FileWriter(destinationFileName));

            String line;
            while ((line = br.readLine()) != null) {
                pw.write(line);
                pw.println();
            }

            br.close();
            pw.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public MobileTopUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPNoLabelMT = new javax.swing.JLabel();
        jPNoTextFieldMT = new javax.swing.JTextField();
        jRAmountLabelMT = new javax.swing.JLabel();
        jRAmountTextFieldMT = new javax.swing.JTextField();
        jSubmitButtonMT = new javax.swing.JButton();
        jClearPNButtonMT = new javax.swing.JButton();
        jClearRAButtonMT = new javax.swing.JButton();
        jBackButtonMT = new javax.swing.JButton();
        jLogOutButtonMT = new javax.swing.JButton();
        jButton1MT = new javax.swing.JButton();
        jButton2MT = new javax.swing.JButton();
        jButton3MT = new javax.swing.JButton();
        jButton4MT = new javax.swing.JButton();
        jButton5MT = new javax.swing.JButton();
        jButton6MT = new javax.swing.JButton();
        jButton7MT = new javax.swing.JButton();
        jButton8MT = new javax.swing.JButton();
        jButton9MT = new javax.swing.JButton();
        jButton0MT = new javax.swing.JButton();
        jKeyBoardLabelMT = new javax.swing.JLabel();
        jBackgroundLabelMT = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mobile Top Up");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 650, 50));

        jPNoLabelMT.setBackground(new java.awt.Color(255, 255, 255));
        jPNoLabelMT.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jPNoLabelMT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPNoLabelMT.setText("Phone Number");
        jPNoLabelMT.setOpaque(true);
        jPanel1.add(jPNoLabelMT, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 250, 40));

        jPNoTextFieldMT.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jPNoTextFieldMT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPNoTextFieldMT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPNoTextFieldMTMouseClicked(evt);
            }
        });
        jPNoTextFieldMT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPNoTextFieldMTActionPerformed(evt);
            }
        });
        jPanel1.add(jPNoTextFieldMT, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 200, 40));

        jRAmountLabelMT.setBackground(new java.awt.Color(255, 255, 255));
        jRAmountLabelMT.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jRAmountLabelMT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRAmountLabelMT.setText("Recharge Amount");
        jRAmountLabelMT.setOpaque(true);
        jPanel1.add(jRAmountLabelMT, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 250, 40));

        jRAmountTextFieldMT.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jRAmountTextFieldMT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jRAmountTextFieldMT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRAmountTextFieldMTMouseClicked(evt);
            }
        });
        jRAmountTextFieldMT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRAmountTextFieldMTActionPerformed(evt);
            }
        });
        jPanel1.add(jRAmountTextFieldMT, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 200, 40));

        jSubmitButtonMT.setBackground(new java.awt.Color(0, 153, 0));
        jSubmitButtonMT.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jSubmitButtonMT.setForeground(new java.awt.Color(255, 255, 255));
        jSubmitButtonMT.setText("Submit");
        jSubmitButtonMT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubmitButtonMTActionPerformed(evt);
            }
        });
        jPanel1.add(jSubmitButtonMT, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 190, 50));

        jClearPNButtonMT.setBackground(new java.awt.Color(0, 0, 0));
        jClearPNButtonMT.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jClearPNButtonMT.setForeground(new java.awt.Color(255, 255, 255));
        jClearPNButtonMT.setText("Clear");
        jClearPNButtonMT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClearPNButtonMTActionPerformed(evt);
            }
        });
        jPanel1.add(jClearPNButtonMT, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, 70, 40));

        jClearRAButtonMT.setBackground(new java.awt.Color(0, 0, 0));
        jClearRAButtonMT.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jClearRAButtonMT.setForeground(new java.awt.Color(255, 255, 255));
        jClearRAButtonMT.setText("Clear");
        jClearRAButtonMT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClearRAButtonMTActionPerformed(evt);
            }
        });
        jPanel1.add(jClearRAButtonMT, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, 70, 40));

        jBackButtonMT.setBackground(new java.awt.Color(0, 0, 0));
        jBackButtonMT.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jBackButtonMT.setForeground(new java.awt.Color(255, 255, 255));
        jBackButtonMT.setText("Back");
        jBackButtonMT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBackButtonMTActionPerformed(evt);
            }
        });
        jPanel1.add(jBackButtonMT, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, 190, 50));

        jLogOutButtonMT.setBackground(new java.awt.Color(255, 0, 0));
        jLogOutButtonMT.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLogOutButtonMT.setForeground(new java.awt.Color(255, 255, 255));
        jLogOutButtonMT.setText("Log Out");
        jLogOutButtonMT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogOutButtonMTActionPerformed(evt);
            }
        });
        jPanel1.add(jLogOutButtonMT, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 490, 190, 50));

        jButton1MT.setBackground(new java.awt.Color(0, 0, 0));
        jButton1MT.setFont(new java.awt.Font("Agency FB", 0, 40)); // NOI18N
        jButton1MT.setForeground(new java.awt.Color(255, 255, 255));
        jButton1MT.setText("1");
        jButton1MT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1MTActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1MT, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 60, 40));

        jButton2MT.setBackground(new java.awt.Color(0, 0, 0));
        jButton2MT.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jButton2MT.setForeground(new java.awt.Color(255, 255, 255));
        jButton2MT.setText("2");
        jButton2MT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2MTActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2MT, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 60, 40));

        jButton3MT.setBackground(new java.awt.Color(0, 0, 0));
        jButton3MT.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jButton3MT.setForeground(new java.awt.Color(255, 255, 255));
        jButton3MT.setText("3");
        jButton3MT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3MTActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3MT, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 60, 40));

        jButton4MT.setBackground(new java.awt.Color(0, 0, 0));
        jButton4MT.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jButton4MT.setForeground(new java.awt.Color(255, 255, 255));
        jButton4MT.setText("4");
        jButton4MT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4MTActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4MT, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 60, 40));

        jButton5MT.setBackground(new java.awt.Color(0, 0, 0));
        jButton5MT.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jButton5MT.setForeground(new java.awt.Color(255, 255, 255));
        jButton5MT.setText("5");
        jButton5MT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5MTActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5MT, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 60, 40));

        jButton6MT.setBackground(new java.awt.Color(0, 0, 0));
        jButton6MT.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jButton6MT.setForeground(new java.awt.Color(255, 255, 255));
        jButton6MT.setText("6");
        jButton6MT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6MTActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6MT, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 60, 40));

        jButton7MT.setBackground(new java.awt.Color(0, 0, 0));
        jButton7MT.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jButton7MT.setForeground(new java.awt.Color(255, 255, 255));
        jButton7MT.setText("7");
        jButton7MT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7MTActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7MT, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 60, 40));

        jButton8MT.setBackground(new java.awt.Color(0, 0, 0));
        jButton8MT.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jButton8MT.setForeground(new java.awt.Color(255, 255, 255));
        jButton8MT.setText("8");
        jButton8MT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8MTActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8MT, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, 60, 40));

        jButton9MT.setBackground(new java.awt.Color(0, 0, 0));
        jButton9MT.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jButton9MT.setForeground(new java.awt.Color(255, 255, 255));
        jButton9MT.setText("9");
        jButton9MT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9MTActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9MT, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, 60, 40));

        jButton0MT.setBackground(new java.awt.Color(0, 0, 0));
        jButton0MT.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jButton0MT.setForeground(new java.awt.Color(255, 255, 255));
        jButton0MT.setText("0");
        jButton0MT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton0MTActionPerformed(evt);
            }
        });
        jPanel1.add(jButton0MT, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 490, 60, 40));

        jKeyBoardLabelMT.setBackground(new java.awt.Color(255, 255, 255));
        jKeyBoardLabelMT.setOpaque(true);
        jPanel1.add(jKeyBoardLabelMT, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 340, 180));

        jBackgroundLabelMT.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hebron Hossain Hamim\\Desktop\\ATM Project\\Images\\bnwb.jpg")); // NOI18N
        jPanel1.add(jBackgroundLabelMT, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2MTActionPerformed
        // TODO add your handling code here:
        if (mouse1 >= 1) {
            number1 = jPNoTextFieldMT.getText() + "2";
            jPNoTextFieldMT.setText(number1);
        } else if (mouse2 >= 1) {
            number2 = jRAmountTextFieldMT.getText() + "2";
            jRAmountTextFieldMT.setText(number2);
        }
    }//GEN-LAST:event_jButton2MTActionPerformed

    private void jButton3MTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3MTActionPerformed
        // TODO add your handling code here:
        if (mouse1 >= 1) {
            number1 = jPNoTextFieldMT.getText() + "3";
            jPNoTextFieldMT.setText(number1);
        } else if (mouse2 >= 1) {
            number2 = jRAmountTextFieldMT.getText() + "3";
            jRAmountTextFieldMT.setText(number2);
        }
    }//GEN-LAST:event_jButton3MTActionPerformed

    private void jButton1MTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1MTActionPerformed
        // TODO add your handling code here:
        if (mouse1 >= 1) {
            number1 = jPNoTextFieldMT.getText() + "1";
            jPNoTextFieldMT.setText(number1);
        } else if (mouse2 >= 1) {
            number2 = jRAmountTextFieldMT.getText() + "1";
            jRAmountTextFieldMT.setText(number2);
        }
    }//GEN-LAST:event_jButton1MTActionPerformed

    private void jButton4MTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4MTActionPerformed
        // TODO add your handling code here:
        if (mouse1 >= 1) {
            number1 = jPNoTextFieldMT.getText() + "4";
            jPNoTextFieldMT.setText(number1);
        } else if (mouse2 >= 1) {
            number2 = jRAmountTextFieldMT.getText() + "4";
            jRAmountTextFieldMT.setText(number2);
        }
    }//GEN-LAST:event_jButton4MTActionPerformed

    private void jButton5MTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5MTActionPerformed
        // TODO add your handling code here:
        if (mouse1 >= 1) {
            number1 = jPNoTextFieldMT.getText() + "5";
            jPNoTextFieldMT.setText(number1);
        } else if (mouse2 >= 1) {
            number2 = jRAmountTextFieldMT.getText() + "5";
            jRAmountTextFieldMT.setText(number2);
        }
    }//GEN-LAST:event_jButton5MTActionPerformed

    private void jButton6MTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6MTActionPerformed
        // TODO add your handling code here:
        if (mouse1 >= 1) {
            number1 = jPNoTextFieldMT.getText() + "6";
            jPNoTextFieldMT.setText(number1);
        } else if (mouse2 >= 1) {
            number2 = jRAmountTextFieldMT.getText() + "6";
            jRAmountTextFieldMT.setText(number2);
        }
    }//GEN-LAST:event_jButton6MTActionPerformed

    private void jButton7MTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7MTActionPerformed
        // TODO add your handling code here:
        if (mouse1 >= 1) {
            number1 = jPNoTextFieldMT.getText() + "7";
            jPNoTextFieldMT.setText(number1);
        } else if (mouse2 >= 1) {
            number2 = jRAmountTextFieldMT.getText() + "7";
            jRAmountTextFieldMT.setText(number2);
        }
    }//GEN-LAST:event_jButton7MTActionPerformed

    private void jButton8MTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8MTActionPerformed
        // TODO add your handling code here:
        if (mouse1 >= 1) {
            number1 = jPNoTextFieldMT.getText() + "8";
            jPNoTextFieldMT.setText(number1);
        } else if (mouse2 >= 1) {
            number2 = jRAmountTextFieldMT.getText() + "8";
            jRAmountTextFieldMT.setText(number2);
        }
    }//GEN-LAST:event_jButton8MTActionPerformed

    private void jButton9MTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9MTActionPerformed
        // TODO add your handling code here:
        if (mouse1 >= 1) {
            number1 = jPNoTextFieldMT.getText() + "9";
            jPNoTextFieldMT.setText(number1);
        } else if (mouse2 >= 1) {
            number2 = jRAmountTextFieldMT.getText() + "9";
            jRAmountTextFieldMT.setText(number2);
        }
    }//GEN-LAST:event_jButton9MTActionPerformed

    private void jButton0MTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton0MTActionPerformed
        // TODO add your handling code here:
        if (mouse1 >= 1) {
            number1 = jPNoTextFieldMT.getText() + "0";
            jPNoTextFieldMT.setText(number1);
        } else if (mouse2 >= 1) {
            number2 = jRAmountTextFieldMT.getText() + "0";
            jRAmountTextFieldMT.setText(number2);
        }
    }//GEN-LAST:event_jButton0MTActionPerformed

    private void jPNoTextFieldMTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPNoTextFieldMTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPNoTextFieldMTActionPerformed

    private void jPNoTextFieldMTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPNoTextFieldMTMouseClicked
        // TODO add your handling code here:
        mouse1 = 1;
        mouse2 = 0;
    }//GEN-LAST:event_jPNoTextFieldMTMouseClicked

    private void jRAmountTextFieldMTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRAmountTextFieldMTMouseClicked
        // TODO add your handling code here:
        mouse1 = 0;
        mouse2 = 1;
    }//GEN-LAST:event_jRAmountTextFieldMTMouseClicked

    private void jRAmountTextFieldMTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRAmountTextFieldMTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRAmountTextFieldMTActionPerformed

    private void jClearPNButtonMTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClearPNButtonMTActionPerformed
        // TODO add your handling code here:
        jPNoTextFieldMT.setText("");
        number1 = "";
    }//GEN-LAST:event_jClearPNButtonMTActionPerformed

    private void jClearRAButtonMTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClearRAButtonMTActionPerformed
        // TODO add your handling code here:
        jRAmountTextFieldMT.setText("");
        number2 = "";
    }//GEN-LAST:event_jClearRAButtonMTActionPerformed

    private void jBackButtonMTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBackButtonMTActionPerformed
        // TODO add your handling code here:
        Home h = new Home(userName, pass);
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBackButtonMTActionPerformed

    private void jSubmitButtonMTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubmitButtonMTActionPerformed
        // TODO add your handling code here:

        String myline = "";
        String otherpart = "";
        try {
            FileReader fr = new FileReader("temp.txt");
            BufferedReader br = new BufferedReader(fr);
            String line;

            while ((line = br.readLine()) != null) {
                arr1 = line.split("#");
                if (arr1[0].equals(userName) && arr1[1].equals(pass)) {
                    myline = line;
                    df = Double.parseDouble(arr1[3]);
                    System.out.println(df);
                } else {
                    otherpart += line + "$";
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(CashWithdraw.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        du = Double.parseDouble(number2);
        if (du <= df) {
            if (du <= 500) {
                if(number1.startsWith(pass))
                mr = mcw.submoney(df, du);
                cv = String.valueOf(mr);
                System.out.println(cv);

                String myarr[] = myline.split("#");
                myarr[3] = cv;
                myline = myarr[0] + "#" + myarr[1] + "#" + myarr[2] + "#" + myarr[3] + "#" + myarr[4] + "#" + myarr[5] + "$";

                otherpart += myline;

                try {

                    PrintWriter pw = new PrintWriter(new FileWriter("temp.txt"));

                    String linearr[] = otherpart.split("[$]");
                    for (int lineno = 0; lineno < linearr.length; lineno++) {
                        pw.write(linearr[lineno]);
                        pw.println();
                    }
                    pw.close();
                } catch (Exception e) {
                    e.printStackTrace();
                }

                String sourceFileName = "temp.txt";
                String destinationFileName = "login.txt";

                try {
                    BufferedReader br = new BufferedReader(new FileReader(sourceFileName));
                    PrintWriter pw = new PrintWriter(new FileWriter(destinationFileName));

                    String line;
                    while ((line = br.readLine()) != null) {
                        pw.write(line);
                        pw.println();
                    }

                    br.close();
                    pw.close();
                } catch (Exception e) {
                    e.printStackTrace();
                }
                
                mcw.history(userName, pass, "Mobile Top Up", du);
                JOptionPane.showMessageDialog(rootPane, "Mobile top Up Successfull");
                
            } else {
                JOptionPane.showMessageDialog(rootPane, "Top Up Amount Excedded.\nPlease Tou Up 500 BDT At A Time.");
            }

        } else {
            JOptionPane.showMessageDialog(rootPane, "Insufficient Amount.\nPlease Check Balance First.");
        }
    }//GEN-LAST:event_jSubmitButtonMTActionPerformed

    private void jLogOutButtonMTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLogOutButtonMTActionPerformed
        // TODO add your handling code here:
        lcw.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLogOutButtonMTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MobileTopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MobileTopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MobileTopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MobileTopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MobileTopUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBackButtonMT;
    private javax.swing.JLabel jBackgroundLabelMT;
    private javax.swing.JButton jButton0MT;
    private javax.swing.JButton jButton1MT;
    private javax.swing.JButton jButton2MT;
    private javax.swing.JButton jButton3MT;
    private javax.swing.JButton jButton4MT;
    private javax.swing.JButton jButton5MT;
    private javax.swing.JButton jButton6MT;
    private javax.swing.JButton jButton7MT;
    private javax.swing.JButton jButton8MT;
    private javax.swing.JButton jButton9MT;
    private javax.swing.JButton jClearPNButtonMT;
    private javax.swing.JButton jClearRAButtonMT;
    private javax.swing.JLabel jKeyBoardLabelMT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jLogOutButtonMT;
    private javax.swing.JLabel jPNoLabelMT;
    private javax.swing.JTextField jPNoTextFieldMT;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jRAmountLabelMT;
    private javax.swing.JTextField jRAmountTextFieldMT;
    private javax.swing.JButton jSubmitButtonMT;
    // End of variables declaration//GEN-END:variables
}
