/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Hebron Hossain Hamim
 */
public class PinChange extends javax.swing.JFrame {

    /**
     * Creates new form PinChange
     */
    
    private String userName;
    private String pass;
    String number1, number2, cv;
    LogIn lcw = new LogIn();
    Method mcw = new Method();
    String arr1[] = new String[40];
    double df, du, mr;
    int mouse1, mouse2, mouse3;
    String pass1;
    
    
    public PinChange(String userName, String pass) {
        this.userName = userName;
        this.pass = pass;
        initComponents();
        
        jKeyBoardLabelPC.setVisible(false);
        jButton0PC.setVisible(false);
        jButton1PC.setVisible(false);
        jButton2PC.setVisible(false);
        jButton3PC.setVisible(false);
        jButton4PC.setVisible(false);
        jButton5PC.setVisible(false);
        jButton6PC.setVisible(false);
        jButton7PC.setVisible(false);
        jButton8PC.setVisible(false);
        jButton9PC.setVisible(false);

        String sourceFileName = "login.txt";
        String destinationFileName = "temp.txt";

        try {
            BufferedReader br = new BufferedReader(new FileReader(sourceFileName));
            PrintWriter pw = new PrintWriter(new FileWriter(destinationFileName));

            String line;
            while ((line = br.readLine()) != null) {
                pw.write(line);
                pw.println();
            }

            br.close();
            pw.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    
    public PinChange() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPinChangeLabelPC = new javax.swing.JLabel();
        jEnterPinLabelPC = new javax.swing.JLabel();
        jPasswordFieldPC = new javax.swing.JPasswordField();
        jSubmitButtonPC = new javax.swing.JButton();
        jClearButtonPC = new javax.swing.JButton();
        jBackButtonPC = new javax.swing.JButton();
        jLogOutButtonPC = new javax.swing.JButton();
        jButton1PC = new javax.swing.JButton();
        jButton2PC = new javax.swing.JButton();
        jButton3PC = new javax.swing.JButton();
        jButton4PC = new javax.swing.JButton();
        jButton5PC = new javax.swing.JButton();
        jButton6PC = new javax.swing.JButton();
        jButton7PC = new javax.swing.JButton();
        jButton8PC = new javax.swing.JButton();
        jButton9PC = new javax.swing.JButton();
        jButton0PC = new javax.swing.JButton();
        jKeyBoardLabelPC = new javax.swing.JLabel();
        jBackgroundLabelPC = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPinChangeLabelPC.setBackground(new java.awt.Color(255, 255, 255));
        jPinChangeLabelPC.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jPinChangeLabelPC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPinChangeLabelPC.setText("Pin Change");
        jPinChangeLabelPC.setOpaque(true);
        jPanel1.add(jPinChangeLabelPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 650, 50));

        jEnterPinLabelPC.setBackground(new java.awt.Color(255, 255, 255));
        jEnterPinLabelPC.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jEnterPinLabelPC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jEnterPinLabelPC.setText("Enter Your Current Pin");
        jEnterPinLabelPC.setOpaque(true);
        jPanel1.add(jEnterPinLabelPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 250, 40));

        jPasswordFieldPC.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jPasswordFieldPC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordFieldPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldPCActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordFieldPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 200, 40));

        jSubmitButtonPC.setBackground(new java.awt.Color(0, 153, 0));
        jSubmitButtonPC.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jSubmitButtonPC.setForeground(new java.awt.Color(255, 255, 255));
        jSubmitButtonPC.setText("Submit");
        jSubmitButtonPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubmitButtonPCActionPerformed(evt);
            }
        });
        jPanel1.add(jSubmitButtonPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 190, 50));

        jClearButtonPC.setBackground(new java.awt.Color(0, 0, 0));
        jClearButtonPC.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jClearButtonPC.setForeground(new java.awt.Color(255, 255, 255));
        jClearButtonPC.setText("Clear");
        jClearButtonPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClearButtonPCActionPerformed(evt);
            }
        });
        jPanel1.add(jClearButtonPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, 70, 40));

        jBackButtonPC.setBackground(new java.awt.Color(0, 0, 0));
        jBackButtonPC.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jBackButtonPC.setForeground(new java.awt.Color(255, 255, 255));
        jBackButtonPC.setText("Back");
        jBackButtonPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBackButtonPCActionPerformed(evt);
            }
        });
        jPanel1.add(jBackButtonPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, 190, 50));

        jLogOutButtonPC.setBackground(new java.awt.Color(255, 0, 0));
        jLogOutButtonPC.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLogOutButtonPC.setForeground(new java.awt.Color(255, 255, 255));
        jLogOutButtonPC.setText("Log Out");
        jLogOutButtonPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogOutButtonPCActionPerformed(evt);
            }
        });
        jPanel1.add(jLogOutButtonPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 490, 190, 50));

        jButton1PC.setBackground(new java.awt.Color(0, 0, 0));
        jButton1PC.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jButton1PC.setForeground(new java.awt.Color(255, 255, 255));
        jButton1PC.setText("1");
        jButton1PC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1PCActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1PC, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 60, 40));

        jButton2PC.setBackground(new java.awt.Color(0, 0, 0));
        jButton2PC.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jButton2PC.setForeground(new java.awt.Color(255, 255, 255));
        jButton2PC.setText("2");
        jButton2PC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2PCActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2PC, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 60, 40));

        jButton3PC.setBackground(new java.awt.Color(0, 0, 0));
        jButton3PC.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jButton3PC.setForeground(new java.awt.Color(255, 255, 255));
        jButton3PC.setText("3");
        jButton3PC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3PCActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3PC, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 60, 40));

        jButton4PC.setBackground(new java.awt.Color(0, 0, 0));
        jButton4PC.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jButton4PC.setForeground(new java.awt.Color(255, 255, 255));
        jButton4PC.setText("4");
        jButton4PC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4PCActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4PC, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 60, 40));

        jButton5PC.setBackground(new java.awt.Color(0, 0, 0));
        jButton5PC.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jButton5PC.setForeground(new java.awt.Color(255, 255, 255));
        jButton5PC.setText("5");
        jButton5PC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5PCActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5PC, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 60, 40));

        jButton6PC.setBackground(new java.awt.Color(0, 0, 0));
        jButton6PC.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jButton6PC.setForeground(new java.awt.Color(255, 255, 255));
        jButton6PC.setText("6");
        jButton6PC.setToolTipText("");
        jButton6PC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6PCActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6PC, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, -1, 40));

        jButton7PC.setBackground(new java.awt.Color(0, 0, 0));
        jButton7PC.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jButton7PC.setForeground(new java.awt.Color(255, 255, 255));
        jButton7PC.setText("7");
        jButton7PC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7PCActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7PC, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 60, 40));

        jButton8PC.setBackground(new java.awt.Color(0, 0, 0));
        jButton8PC.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jButton8PC.setForeground(new java.awt.Color(255, 255, 255));
        jButton8PC.setText("8");
        jButton8PC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8PCActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8PC, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, 60, 40));

        jButton9PC.setBackground(new java.awt.Color(0, 0, 0));
        jButton9PC.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jButton9PC.setForeground(new java.awt.Color(255, 255, 255));
        jButton9PC.setText("9");
        jButton9PC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9PCActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9PC, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, 60, 40));

        jButton0PC.setBackground(new java.awt.Color(0, 0, 0));
        jButton0PC.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jButton0PC.setForeground(new java.awt.Color(255, 255, 255));
        jButton0PC.setText("0");
        jButton0PC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton0PCActionPerformed(evt);
            }
        });
        jPanel1.add(jButton0PC, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 490, 60, 40));

        jKeyBoardLabelPC.setBackground(new java.awt.Color(255, 255, 255));
        jKeyBoardLabelPC.setOpaque(true);
        jPanel1.add(jKeyBoardLabelPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 340, 180));

        jBackgroundLabelPC.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hebron Hossain Hamim\\Desktop\\ATM Project\\Images\\bnwb.jpg")); // NOI18N
        jPanel1.add(jBackgroundLabelPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4PCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4PCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4PCActionPerformed

    private void jSubmitButtonPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubmitButtonPCActionPerformed
        // TODO add your handling code here:
        pass1 = jPasswordFieldPC.getText();
        boolean isvalid = false;

        if (pass.equals(pass1)) {
            JOptionPane.showMessageDialog(rootPane, "Password Matched ");
            isvalid = true;
            PinChangePOP pop = new PinChangePOP(userName,pass);
            pop.setVisible(true);
            this.dispose();
        }
        else if (isvalid == false) {
            JOptionPane.showMessageDialog(rootPane, "Passwor Is Wrong");
        }
    }//GEN-LAST:event_jSubmitButtonPCActionPerformed

    private void jButton1PCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1PCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1PCActionPerformed

    private void jButton2PCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2PCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2PCActionPerformed

    private void jButton3PCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3PCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3PCActionPerformed

    private void jButton5PCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5PCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5PCActionPerformed

    private void jButton6PCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6PCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6PCActionPerformed

    private void jButton7PCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7PCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7PCActionPerformed

    private void jButton8PCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8PCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8PCActionPerformed

    private void jButton9PCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9PCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9PCActionPerformed

    private void jButton0PCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton0PCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton0PCActionPerformed

    private void jPasswordFieldPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldPCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldPCActionPerformed

    private void jClearButtonPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClearButtonPCActionPerformed
        // TODO add your handling code here:
        jPasswordFieldPC.setText("");
        pass1 = "";
    }//GEN-LAST:event_jClearButtonPCActionPerformed

    private void jBackButtonPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBackButtonPCActionPerformed
        // TODO add your handling code here:
        Home h = new Home(userName, pass);
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBackButtonPCActionPerformed

    private void jLogOutButtonPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLogOutButtonPCActionPerformed
        // TODO add your handling code here:
        lcw.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLogOutButtonPCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PinChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PinChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PinChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PinChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PinChange().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBackButtonPC;
    private javax.swing.JLabel jBackgroundLabelPC;
    private javax.swing.JButton jButton0PC;
    private javax.swing.JButton jButton1PC;
    private javax.swing.JButton jButton2PC;
    private javax.swing.JButton jButton3PC;
    private javax.swing.JButton jButton4PC;
    private javax.swing.JButton jButton5PC;
    private javax.swing.JButton jButton6PC;
    private javax.swing.JButton jButton7PC;
    private javax.swing.JButton jButton8PC;
    private javax.swing.JButton jButton9PC;
    private javax.swing.JButton jClearButtonPC;
    private javax.swing.JLabel jEnterPinLabelPC;
    private javax.swing.JLabel jKeyBoardLabelPC;
    private javax.swing.JButton jLogOutButtonPC;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFieldPC;
    private javax.swing.JLabel jPinChangeLabelPC;
    private javax.swing.JButton jSubmitButtonPC;
    // End of variables declaration//GEN-END:variables
}
