/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Hebron Hossain Hamim
 */
public class Statement extends javax.swing.JFrame {

    /**
     * Creates new form Statement
     */
    private String userName;
    private String pass;
    String amount, typ, tnxid;
    LogIn lcw = new LogIn();
    Method mcw = new Method();
    String arr1[] = new String[40];

    public Statement(String userName, String pass) {
        this.userName = userName;
        this.pass = pass;
        initComponents();

        jKeyBoardLabelS.setVisible(false);
        jButton0S.setVisible(false);
        jButton1S.setVisible(false);
        jButton2S.setVisible(false);
        jButton3S.setVisible(false);
        jButton4S.setVisible(false);
        jButton5S.setVisible(false);
        jButton6S.setVisible(false);
        jButton7S.setVisible(false);
        jButton8S.setVisible(false);
        jButton9S.setVisible(false);

        try {
            FileReader fr = new FileReader("history.txt");
            BufferedReader br = new BufferedReader(fr);
            String line;
            while ((line = br.readLine()) != null) {
                arr1 = line.split("#");
                if (arr1[0].equals(userName) && arr1[1].equals(pass)) {
                    typ = arr1[2];
                    amount = arr1[3];
                    tnxid = arr1[4];
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(CashWithdraw.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public Statement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jStatementLabelS = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldS1 = new javax.swing.JTextField();
        jTextFieldS2 = new javax.swing.JTextField();
        jTextFieldS3 = new javax.swing.JTextField();
        jShowHistoryButton = new javax.swing.JButton();
        jBackButtonS = new javax.swing.JButton();
        jLogOutButtonS = new javax.swing.JButton();
        jButton1S = new javax.swing.JButton();
        jButton2S = new javax.swing.JButton();
        jButton3S = new javax.swing.JButton();
        jButton4S = new javax.swing.JButton();
        jButton5S = new javax.swing.JButton();
        jButton6S = new javax.swing.JButton();
        jButton7S = new javax.swing.JButton();
        jButton8S = new javax.swing.JButton();
        jButton9S = new javax.swing.JButton();
        jButton0S = new javax.swing.JButton();
        jKeyBoardLabelS = new javax.swing.JLabel();
        jBackgroundLabelS = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jStatementLabelS.setBackground(new java.awt.Color(255, 255, 255));
        jStatementLabelS.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jStatementLabelS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jStatementLabelS.setText("Statement");
        jStatementLabelS.setOpaque(true);
        jPanel1.add(jStatementLabelS, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 650, 50));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Last Transaction History:");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 190, -1));

        jTextFieldS1.setFont(new java.awt.Font("Agency FB", 0, 30)); // NOI18N
        jTextFieldS1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldS1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldS1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 340, 40));

        jTextFieldS2.setFont(new java.awt.Font("Agency FB", 0, 30)); // NOI18N
        jTextFieldS2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldS2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldS2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldS2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 340, 40));

        jTextFieldS3.setFont(new java.awt.Font("Agency FB", 0, 30)); // NOI18N
        jTextFieldS3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldS3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldS3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldS3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 340, 40));

        jShowHistoryButton.setBackground(new java.awt.Color(0, 0, 0));
        jShowHistoryButton.setFont(new java.awt.Font("Agency FB", 1, 30)); // NOI18N
        jShowHistoryButton.setForeground(new java.awt.Color(255, 255, 255));
        jShowHistoryButton.setText("Show History");
        jShowHistoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jShowHistoryButtonActionPerformed(evt);
            }
        });
        jPanel1.add(jShowHistoryButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 190, 50));

        jBackButtonS.setBackground(new java.awt.Color(0, 0, 0));
        jBackButtonS.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jBackButtonS.setForeground(new java.awt.Color(255, 255, 255));
        jBackButtonS.setText("Back");
        jBackButtonS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBackButtonSActionPerformed(evt);
            }
        });
        jPanel1.add(jBackButtonS, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, 190, 50));

        jLogOutButtonS.setBackground(new java.awt.Color(255, 0, 0));
        jLogOutButtonS.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLogOutButtonS.setForeground(new java.awt.Color(255, 255, 255));
        jLogOutButtonS.setText("Log Out");
        jLogOutButtonS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogOutButtonSActionPerformed(evt);
            }
        });
        jPanel1.add(jLogOutButtonS, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 490, 190, 50));

        jButton1S.setBackground(new java.awt.Color(0, 0, 0));
        jButton1S.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jButton1S.setForeground(new java.awt.Color(255, 255, 255));
        jButton1S.setText("1");
        jPanel1.add(jButton1S, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 60, 40));

        jButton2S.setBackground(new java.awt.Color(0, 0, 0));
        jButton2S.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jButton2S.setForeground(new java.awt.Color(255, 255, 255));
        jButton2S.setText("2");
        jPanel1.add(jButton2S, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 60, 40));

        jButton3S.setBackground(new java.awt.Color(0, 0, 0));
        jButton3S.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jButton3S.setForeground(new java.awt.Color(255, 255, 255));
        jButton3S.setText("3");
        jPanel1.add(jButton3S, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 60, 40));

        jButton4S.setBackground(new java.awt.Color(0, 0, 0));
        jButton4S.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jButton4S.setForeground(new java.awt.Color(255, 255, 255));
        jButton4S.setText("4");
        jPanel1.add(jButton4S, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 60, 40));

        jButton5S.setBackground(new java.awt.Color(0, 0, 0));
        jButton5S.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jButton5S.setForeground(new java.awt.Color(255, 255, 255));
        jButton5S.setText("5");
        jPanel1.add(jButton5S, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 60, -1));

        jButton6S.setBackground(new java.awt.Color(0, 0, 0));
        jButton6S.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jButton6S.setForeground(new java.awt.Color(255, 255, 255));
        jButton6S.setText("6");
        jPanel1.add(jButton6S, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 60, 40));

        jButton7S.setBackground(new java.awt.Color(0, 0, 0));
        jButton7S.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jButton7S.setForeground(new java.awt.Color(255, 255, 255));
        jButton7S.setText("7");
        jPanel1.add(jButton7S, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 60, 40));

        jButton8S.setBackground(new java.awt.Color(0, 0, 0));
        jButton8S.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jButton8S.setForeground(new java.awt.Color(255, 255, 255));
        jButton8S.setText("8");
        jPanel1.add(jButton8S, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, 60, 40));

        jButton9S.setBackground(new java.awt.Color(0, 0, 0));
        jButton9S.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jButton9S.setForeground(new java.awt.Color(255, 255, 255));
        jButton9S.setText("9");
        jButton9S.setToolTipText("");
        jPanel1.add(jButton9S, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, 60, 40));

        jButton0S.setBackground(new java.awt.Color(0, 0, 0));
        jButton0S.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jButton0S.setForeground(new java.awt.Color(255, 255, 255));
        jButton0S.setText("0");
        jPanel1.add(jButton0S, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 490, 60, 40));

        jKeyBoardLabelS.setBackground(new java.awt.Color(255, 255, 255));
        jKeyBoardLabelS.setOpaque(true);
        jPanel1.add(jKeyBoardLabelS, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 340, 180));

        jBackgroundLabelS.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hebron Hossain Hamim\\Desktop\\ATM Project\\Images\\bnwb.jpg")); // NOI18N
        jPanel1.add(jBackgroundLabelS, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldS1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldS1ActionPerformed

    private void jShowHistoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jShowHistoryButtonActionPerformed
        // TODO add your handling code here:
        jTextFieldS1.setText(typ);
        jTextFieldS2.setText("  Amount : " + amount + " BDT");
        jTextFieldS3.setText("  Transaction ID : " + tnxid);

    }//GEN-LAST:event_jShowHistoryButtonActionPerformed

    private void jTextFieldS2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldS2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldS2ActionPerformed

    private void jTextFieldS3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldS3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldS3ActionPerformed

    private void jBackButtonSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBackButtonSActionPerformed
        // TODO add your handling code here:
        Home h = new Home(userName, pass);
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBackButtonSActionPerformed

    private void jLogOutButtonSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLogOutButtonSActionPerformed
        // TODO add your handling code here:
        lcw.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jLogOutButtonSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Statement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Statement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Statement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Statement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Statement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBackButtonS;
    private javax.swing.JLabel jBackgroundLabelS;
    private javax.swing.JButton jButton0S;
    private javax.swing.JButton jButton1S;
    private javax.swing.JButton jButton2S;
    private javax.swing.JButton jButton3S;
    private javax.swing.JButton jButton4S;
    private javax.swing.JButton jButton5S;
    private javax.swing.JButton jButton6S;
    private javax.swing.JButton jButton7S;
    private javax.swing.JButton jButton8S;
    private javax.swing.JButton jButton9S;
    private javax.swing.JLabel jKeyBoardLabelS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jLogOutButtonS;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jShowHistoryButton;
    private javax.swing.JLabel jStatementLabelS;
    private javax.swing.JTextField jTextFieldS1;
    private javax.swing.JTextField jTextFieldS2;
    private javax.swing.JTextField jTextFieldS3;
    // End of variables declaration//GEN-END:variables
}
